objects/Anthem_API_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Event_Endpoint__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Event Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Anthem API Settings</label>
</CustomObject>

objects/LG_Application__e.object
<CustomObject>
    <description>Platform Event to capture all status changes around LG Applications.</description>
    <fields>
        <fullName>Application_ID__c</fullName>
        <description>Record ID of Application.</description>
        <label>Application ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application_Status_Modified__c</fullName>
        <description>Datetime of Status change.</description>
        <label>Application Status Modified</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Name__c</fullName>
        <description>Field for LG Broker Portal to identify the type of Event.</description>
        <label>Event Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>&apos;LG&quot;</description>
        <label>Line of Business</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payee_TIN__c</fullName>
        <description>Payee broker party.</description>
        <label>Payee TIN</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>US State two char abbreviated.</description>
        <label>State</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Writing_TIN__c</fullName>
        <description>Writing broker party.</description>
        <label>Writing TIN</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>LG Application</label>
    <pluralLabel>LG Applications</pluralLabel>
</CustomObject>

classes/AnthemAPITest.cls
/*
 * Class Name: AnthemAPITest
 * Current Version: 1.0
 * Created Date: October 2019
 * Author: Archima
 * Description: This class has the unit tests for the AnthemAPI class.
 */
@isTest
private class AnthemAPITest {

    @isTest
    static void testPostEvent() {
        Anthem_API_Settings__c anthemAPISettings = Anthem_API_Settings__c.getOrgDefaults();
        anthemAPISettings.Event_Endpoint__c = 'https://test.com';
        upsert anthemAPISettings;

        LG_Application__e lgApplication = new LG_Application__e();
        lgApplication.Event_Name__c = 'APPLICATION_UPDATED';
        lgApplication.Application_ID__c = '123';
        lgApplication.Line_of_Business__c = 'LG';
        lgApplication.Payee_TIN__c = 'ABC';
        lgApplication.Writing_TIN__c = 'DEF';
        lgApplication.State__c = 'VA';
        lgApplication.Application_Status_Modified__c = Date.today();

        HttpResponse httpResponseToken = new HttpResponse();
        httpResponseToken.setBody(LGJiraUtilityMockTest.jiraSuccessResponse);
        httpResponseToken.setStatusCode(200);

        HttpResponse httpResponseEvent = new HttpResponse();
        httpResponseEvent.setStatusCode(200);

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new AnthemAPICalloutMock(new List<HttpResponse>{httpResponseToken, httpResponseEvent}));

        try {
            AnthemAPI.postEvent(JSON.serialize(lgApplication));
        } catch (Exception e) {
            System.assert(false, 'Exception should not have been thrown.');
        }
        
        Test.stopTest();
    }

    public class AnthemAPICalloutMock implements HttpCalloutMock {

        private List<HttpResponse> httpResponses = new List<HttpResponse>();
        private Integer httpResponseIndex = 0;


        public AnthemAPICalloutMock(List<HttpResponse> httpResponses) {
            this.httpResponses = httpResponses;
        }

        public HTTPResponse respond(HTTPRequest request) {
			return httpResponses[httpResponseIndex++];
		}

    }
    
}