objects/Brokerage_and_Consultant1__c.object
<CustomObject>
    <description>Brokerage and Consultant object for Opportunity</description>
    <fields>
        <fullName>Broker_Role__c</fullName>
        <label>Broker Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>General Agent</fullName>
                </value>
                <value>
                    <fullName>Writing Agent</fullName>
                </value>
                <value>
                    <fullName>Account Exec</fullName>
                </value>
                <value>
                    <fullName>Account Manager</fullName>
                </value>
                <value>
                    <fullName>Analyst</fullName>
                </value>
                <value>
                    <fullName>Broker of Record</fullName>
                </value>
                <value>
                    <fullName>Co Broker</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Soliciting Broker</fullName>
                </value>
                <value>
                    <fullName>Marketing Manager</fullName>
                </value>
                <value>
                    <fullName>Service Rep</fullName>
                </value>
                <value>
                    <fullName>Former Broker</fullName>
                </value>
                <value>
                    <fullName>Assistant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Brokerage_Role__c</fullName>
        <label>Brokerage Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Brokerage</fullName>
                </value>
                <value>
                    <fullName>Co-Broker</fullName>
                </value>
                <value>
                    <fullName>Consultancy</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>General Agency</fullName>
                </value>
                <value>
                    <fullName>Producer</fullName>
                </value>
                <value>
                    <fullName>Soliciting Broker</fullName>
                </value>
                <value>
                    <fullName>TPA</fullName>
                </value>
                <value>
                    <fullName>Broker of Record</fullName>
                </value>
                <value>
                    <fullName>Trustee</fullName>
                </value>
                <value>
                    <fullName>Former Broker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Brokerage_and_Consultant11</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brokerage and Consultant</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brokerage and Consultant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ApplicationEventActionTest.cls
/*
 * Class Name: ApplicationEventActionTest
 * Current Version: 1.0
 * Created Date: October 2019
 * Author: Archima
 * Description: This class has the unit tests for the ApplicationEventAction class.
 */
@isTest
private class ApplicationEventActionTest {

    @isTest
    static void testCreateApplicationEvents() {
        Account account = new Account();
        account.Name = 'Test';
        insert account;

        Opportunity opportunity = new Opportunity();
        opportunity.AccountId = account.Id;
        opportunity.Name = 'Test';
        opportunity.StageName = 'Prospecting';
        opportunity.CloseDate = Date.today();
        insert opportunity;

        Brokerage_and_Consultant1__c brokerageConsultant = new Brokerage_and_Consultant1__c();
        brokerageConsultant.Opportunity__c = opportunity.Id;
        brokerageConsultant.Broker_Role__c = ApplicationEventAction.WRITING_AGENT_BROKER_ROLE;
        brokerageConsultant.Brokerage_Role__c = ApplicationEventAction.BROKERAGE_BROKERAGE_ROLE;
        insert brokerageConsultant;

        Order order = new Order();
        order.AccountId = account.Id;
        order.OpportunityId = opportunity.Id;
        order.EffectiveDate = Date.today();
        order.Status = 'Draft';
        insert order;

        Test.startTest();

        // NOTE: ApplicationEventAction.createApplicationEvents() sole purpose is to publish a platform event which can't be asserted.
        try {
            ApplicationEventAction.createApplicationEvents(new List<Id>{order.Id});
        } catch (Exception e) {
            System.assert(false, 'Exception should not have been thrown.');
        }

        Test.stopTest();
    }

}