objects/Brokerage_and_Consultant1__c.object
<CustomObject>
    <description>Brokerage and Consultant object for Opportunity</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Brokerage_and_Consultant11_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Broker_Role__c</fullName>
        <label>Broker Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>General Agent</fullName>
                </value>
                <value>
                    <fullName>Writing Agent</fullName>
                </value>
                <value>
                    <fullName>Account Exec</fullName>
                </value>
                <value>
                    <fullName>Account Manager</fullName>
                </value>
                <value>
                    <fullName>Analyst</fullName>
                </value>
                <value>
                    <fullName>Broker of Record</fullName>
                </value>
                <value>
                    <fullName>Co Broker</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Soliciting Broker</fullName>
                </value>
                <value>
                    <fullName>Marketing Manager</fullName>
                </value>
                <value>
                    <fullName>Service Rep</fullName>
                </value>
                <value>
                    <fullName>Former Broker</fullName>
                </value>
                <value>
                    <fullName>Assistant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Brokerage_Role__c</fullName>
        <label>Brokerage Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Brokerage</fullName>
                </value>
                <value>
                    <fullName>Co-Broker</fullName>
                </value>
                <value>
                    <fullName>Consultancy</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>General Agency</fullName>
                </value>
                <value>
                    <fullName>Producer</fullName>
                </value>
                <value>
                    <fullName>Soliciting Broker</fullName>
                </value>
                <value>
                    <fullName>TPA</fullName>
                </value>
                <value>
                    <fullName>Broker of Record</fullName>
                </value>
                <value>
                    <fullName>Trustee</fullName>
                </value>
                <value>
                    <fullName>Former Broker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Consultant must be a Contact on the selected Brokerage.</inlineHelpText>
        <label>Consultant</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 4) AND 3</booleanFilter>
            <errorMessage>Please select an Active Consultant from the specified Brokerage Account.</errorMessage>
            <filterItems>
                <field>ContactRelationship__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Brokerage__c</valueField>
            </filterItems>
            <filterItems>
                <field>ContactRelationship__c.CONTCANCEL__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>ContactRelationship__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>LG_Brokerage_Consultant_Relationship</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>API User</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ContactRelationship__c</referenceTo>
        <relationshipLabel>Brokerage and Consultant</relationshipLabel>
        <relationshipName>Brokerage_and_Consultant1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <label>Line of Business</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Dental</fullName>
                </value>
                <value>
                    <fullName>Vision</fullName>
                </value>
                <value>
                    <fullName>Life</fullName>
                </value>
                <value>
                    <fullName>STD</fullName>
                </value>
                <value>
                    <fullName>LTD</fullName>
                </value>
                <value>
                    <fullName>FMLA</fullName>
                </value>
                <value>
                    <fullName>AIM</fullName>
                </value>
                <value>
                    <fullName>Expatriate</fullName>
                </value>
                <value>
                    <fullName>Health &amp; Wellness</fullName>
                </value>
                <value>
                    <fullName>Medicare</fullName>
                </value>
                <value>
                    <fullName>Pharmacy</fullName>
                </value>
                <value>
                    <fullName>Stop Loss</fullName>
                </value>
                <value>
                    <fullName>Benefits Admin</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Accident</fullName>
                </value>
                <value>
                    <fullName>Critical Illness</fullName>
                </value>
                <value>
                    <fullName>Hospital Indemnity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Brokerage_and_Consultant11</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brokerage and Consultant</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brokerage and Consultant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ContactRelationship__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Relationships</relationshipLabel>
        <relationshipName>Contact_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account To Contact Relationships</relationshipLabel>
        <relationshipName>Contact_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>State</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Contact Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LG_Application__e.object
<CustomObject>
    <description>Platform Event to capture all status changes around LG Applications.</description>
    <fields>
        <fullName>Application_ID__c</fullName>
        <description>Record ID of Application.</description>
        <label>Application ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application_Status_Description__c</fullName>
        <description>Human friendly description for Status of Application.</description>
        <label>Application Status Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application_Status_Modified__c</fullName>
        <description>Datetime of Status change.</description>
        <label>Application Status Modified</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <description>Status for given Application</description>
        <label>Application Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Name__c</fullName>
        <description>Field for LG Broker Portal to identify the type of Event.</description>
        <label>Event Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>&apos;LG&quot;</description>
        <label>Line of Business</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payee_TIN__c</fullName>
        <description>Payee broker party.</description>
        <label>Payee TIN</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>US State two char abbreviated.</description>
        <label>State</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Writing_TIN__c</fullName>
        <description>Writing broker party.</description>
        <label>Writing TIN</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>LG Application</label>
    <pluralLabel>LG Applications</pluralLabel>
</CustomObject>

classes/ApplicationEventAction.cls
/*
 * Class Name: ApplicationEventAction
 * Current Version: 1.0
 * Created Date: October 2019
 * Author: Archima
 * Description: This class has an invocable method that is used by a process
 * to publish LG Application platform events.
 */
public with sharing class ApplicationEventAction {

    public static final String WRITING_AGENT_BROKER_ROLE = 'Writing Agent';
    public static final String BROKERAGE_BROKERAGE_ROLE = 'Brokerage';

    @InvocableMethod(label='Create Application Events')
    public static void createApplicationEvents(List<Id> orderIds) {
        List<Order> orders = [
            SELECT
            	OpportunityId,
            	OrderNumber,
            	LG_Broker_Portal_Case_Status__c,
            	LG_Broker_Portal_Status_Date__c,
            	LG_Broker_Portal_Status_Event_Type__c,
            	Account.Situs_State_Abbrev__c
           	FROM
            	Order
            WHERE
            	Id IN :orderIds
        ];

        Set<Id> opportunityIds = new Set<Id>();

        for (Order order : orders) {
            opportunityIds.add(order.OpportunityId);
        }

        List<Brokerage_and_Consultant1__c> brokerageConsultants = [
        	SELECT
            	Opportunity__c,
            	Brokerage_Role__c,
            	Broker_Role__c,
            	Consultant__r.Account__r.ENCRYPTID__c,
            	Consultant__r.Contact__r.ENCRYPTID__c
            FROM
            	Brokerage_and_Consultant1__c
            WHERE
                Opportunity__c IN :opportunityIds
            AND
            	(
                	Broker_Role__c = :WRITING_AGENT_BROKER_ROLE
                    OR
            		Brokerage_Role__c = :BROKERAGE_BROKERAGE_ROLE
                )
        ];

        Map<Id, Brokerage_and_Consultant1__c> opportunityBrokerageConsultants = new Map<Id, Brokerage_and_Consultant1__c>();
        Map<Id, Brokerage_and_Consultant1__c> opportunityWritingConsultants = new Map<Id, Brokerage_and_Consultant1__c>();

        for (Brokerage_and_Consultant1__c brokerageConsultant : brokerageConsultants) {
            if (brokerageConsultant.Brokerage_Role__c == BROKERAGE_BROKERAGE_ROLE) {
            	opportunityBrokerageConsultants.put(brokerageConsultant.Opportunity__c, brokerageConsultant);
            }

            if (brokerageConsultant.Broker_Role__c == WRITING_AGENT_BROKER_ROLE) {
				opportunityWritingConsultants.put(brokerageConsultant.Opportunity__c, brokerageConsultant);
            }
        }

        List<LG_Application__e> applicationEvents = new List<LG_Application__e>();

        for (Order order : orders) {
            Brokerage_and_Consultant1__c brokerageConsultant = opportunityBrokerageConsultants.get(order.OpportunityId);
            Brokerage_and_Consultant1__c writingConsultant = opportunityWritingConsultants.get(order.OpportunityId);

            LG_Application__e applicationEvent = new LG_Application__e();
            applicationEvent.Application_ID__c = order.OrderNumber;
            applicationEvent.Application_Status__c = order.LG_Broker_Portal_Case_Status__c;
            applicationEvent.Application_Status_Description__c = order.LG_Broker_Portal_Case_Status__c;
            applicationEvent.Application_Status_Modified__c = order.LG_Broker_Portal_Status_Date__c;
            applicationEvent.Event_Name__c = order.LG_Broker_Portal_Status_Event_Type__c;
            applicationEvent.Line_of_Business__c = 'LG';
            applicationEvent.Payee_TIN__c = (brokerageConsultant == null ? null : brokerageConsultant.Consultant__r.Account__r.ENCRYPTID__c);
            applicationEvent.State__c = order.Account.Situs_State_Abbrev__c;
            applicationEvent.Writing_TIN__c = (writingConsultant == null ? null : writingConsultant.Consultant__r.Contact__r.ENCRYPTID__c);
            applicationEvents.add(applicationEvent);
        }
        
        EventBus.publish(applicationEvents);
    }

}