objects/ContactRelationship__c.object
<CustomObject>
    <fields>
        <fullName>Biiling_Contact_and_Group_Admin__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Biiling Contact and Group Admin</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billing Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <inlineHelpText>To select more than one contact type, hold the control (ctrl) key and select the values.</inlineHelpText>
        <label>Contact Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anthem Account Service Rep</fullName>
                </value>
                <value>
                    <fullName>Anthem Executive Sponsor</fullName>
                </value>
                <value>
                    <fullName>Anthem Secondary Executive Sponsor</fullName>
                </value>
                <value>
                    <fullName>Benefits</fullName>
                </value>
                <value>
                    <fullName>Board Member</fullName>
                </value>
                <value>
                    <fullName>Billing Contact</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
                <value>
                    <fullName>CHRO</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>COO</fullName>
                </value>
                <value>
                    <fullName>Decision Maker</fullName>
                </value>
                <value>
                    <fullName>Finance/CFO</fullName>
                </value>
                <value>
                    <fullName>Group Administrator</fullName>
                </value>
                <value>
                    <fullName>HIPAA Privacy Officer</fullName>
                </value>
                <value>
                    <fullName>HIPAA Rep</fullName>
                </value>
                <value>
                    <fullName>HR Mgr/Dir</fullName>
                </value>
                <value>
                    <fullName>Human Resources</fullName>
                </value>
                <value>
                    <fullName>MEU Contact</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pathways to Health</fullName>
                </value>
                <value>
                    <fullName>President/CEO</fullName>
                </value>
                <value>
                    <fullName>Reference</fullName>
                </value>
                <value>
                    <fullName>Region Dir</fullName>
                </value>
                <value>
                    <fullName>Third Party Admin</fullName>
                </value>
                <value>
                    <fullName>TPA Account Manager</fullName>
                </value>
                <value>
                    <fullName>TPA Claims Analyst</fullName>
                </value>
                <value>
                    <fullName>TPA Client Liaison</fullName>
                </value>
                <value>
                    <fullName>Vice President</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group_Admin__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Group Admin</label>
        <type>Checkbox</type>
    </fields>
    <label>Contact Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ContactRelationshipsHelper.cls
/** Author       ::: Ranjith Kumar
**  Created      ::: 24th Feb 2020
**  Purpose      ::: To Implement the "Billing Contact" and "Group Administrator" functionality for Contact Relationship Object.
**  Version      ::: v1
**/

public class ContactRelationshipsHelper{
    
    /** Author       ::: Ranjith Kumar
    **  Created      ::: 24th Feb 2020
    **  Purpose      ::: To update "Billing_Contact__c" ,"Group_Admin__c" and "Biiling_Contact_and_Group_Admin__c" fields in Contact Relationship Object based on Contact Type field Values.
    **  Execution    ::: Before Insert and Before Update
    **/
    public static void updateContactTypeFields(List<ContactRelationship__c> conRelList,Map<Id,ContactRelationship__c> oldMap,boolean isInsert){
        for(ContactRelationship__c conRel : conRelList){
            if(isInsert || (!isInsert && oldMap.get(conRel.Id).Contact_Type__c!=conRel.Contact_Type__c)){
                if(!conRel.Contact_Type__c.contains('Billing Contact') && conRel.Contact_Type__c!=null && conRel.Contact_Type__c.contains('Group Administrator')){
                    conRel.Group_Admin__c=true;
                }
                if(conRel.Contact_Type__c!=null && !conRel.Contact_Type__c.contains('Group Administrator') && conRel.Group_Admin__c==true){
                    conRel.Group_Admin__c=false;
                }
                if(!conRel.Contact_Type__c.contains('Group Administrator') && conRel.Contact_Type__c!=null && conRel.Contact_Type__c.contains('Billing Contact')){
                    conRel.Billing_Contact__c=true;
                }
                if(conRel.Contact_Type__c!=null && !conRel.Contact_Type__c.contains('Billing Contact') && conRel.Billing_Contact__c==true){
                    conRel.Billing_Contact__c=false;
                }
                if(conRel.Contact_Type__c.contains('Group Administrator') && conRel.Contact_Type__c.contains('Billing Contact')){
                    conRel.Biiling_Contact_and_Group_Admin__c=true;
                }
                if((!conRel.Contact_Type__c.contains('Group Administrator') || !conRel.Contact_Type__c.contains('Billing Contact')) && conRel.Biiling_Contact_and_Group_Admin__c==true && conRel.Contact_Type__c!=null){
                    conRel.Biiling_Contact_and_Group_Admin__c=false;
                }
            }
        }
    }
    
}