objects/LeadConversionReportData__c.object
<CustomObject>
    <description>Object contains the records with all the stages from the report with their amount last month and current month</description>
    <fields>
        <fullName>CurrentMonthAmount__c</fullName>
        <description>Stores the amount of a particular stage of the current month</description>
        <label>CurrentMonthAmount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LastMonthAmount__c</fullName>
        <description>Stores the amount of the particular stage that of last month.</description>
        <label>LastMonthAmount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <description>It stores the month name ,during which the lead conversion rate has been calculated for  a particular stage</description>
        <label>Month</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>LeadConversionReportData</label>
    <nameField>
        <label>Stage</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LeadConversionReportDatas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchCLS_LeadConversionReportData_Test.cls
@isTest
public class BatchCLS_LeadConversionReportData_Test {
    @isTest(SeeAllData='true')
    public static void LeadConversionReportData_Method(){
        
        Opportunity opp = new Opportunity(Name='ApexTestOpp', StageName='stage',Probability = 95, CloseDate=system.today(),Amount = 950000);
        insert opp;
        
        LeadConversionReportData__c leadConversionInfo = new LeadConversionReportData__c(Name = 'stage',Month__c = 'January',CurrentMonthAmount__c = 95000,LastMonthAmount__c= 53433);
        
        insert leadConversionInfo;
        //Test.setCreatedDate(leadConversionInfo.Id, (Date.today() -1).tostartOfMonth());
        System.debug(leadConversionInfo.CreatedDate);
        Test.startTest();
        BatchCLS_LeadConversionReportData leadConversionReportData = new BatchCLS_LeadConversionReportData();
        Database.executeBatch(leadConversionReportData);
        Test.stopTest();
        
    }
}