objects/Open_Enrollment_Meetings__c.object
<CustomObject>
    <description>This object is a container for all individual OE Meetings.  An Account may be associated to 0 to many Open Enrollment Meeting (Groupings).</description>
    <fields>
        <fullName>Anthem_Entity__c</fullName>
        <formula>TEXT(Account__r.Anthem_Entity__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Anthem Entity</label>
        <type>Text</type>
    </fields>
    <label>Open Enrollment Meetings</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>OE Meeting Grouping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Enrollment Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDC_Volunteer_Event__c.object
<CustomObject>
    <description>Used to manage and track vounteer events</description>
    <fields>
        <fullName>Anthem_Entity__c</fullName>
        <formula>OE_Grouping__r.Anthem_Entity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Anthem Entity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Phone_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Meeting Contact Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Meeting Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Facilitator_Being_Recruited__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check box for OE coordinator to indicate that the meeting should go into the pool for ambassador recruitment</description>
        <label>Facilitator Being Recruited</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Facilitator_Feedback_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <description>(LG201427) Please check with dev team before modifing- this field is updated with a force.com site  Facilitator Feedback has been entered into the system</description>
        <label>Facilitator Feedback Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Facilitator_Secured__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used by Open Enrollment to indicate that the facilitator(s) has been secured for the meeting.  This should trigger an email to be sent out to the facilitator</description>
        <label>Facilitator Secured</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Feedback_Not_Received_Within_14_Days__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Feedback Not Received Within 14 Days</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Materials_Delivered__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to indicate a confirmation of shippment email was received.</description>
        <label>Materials Delivered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Materials_Needed__c</fullName>
        <label>Materials Needed</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Promo only needed</fullName>
                </value>
                <value>
                    <fullName>Collateral only needed</fullName>
                </value>
                <value>
                    <fullName>Promo and Collateral Needed</fullName>
                </value>
                <value>
                    <fullName>No Promo or Collateral Needed</fullName>
                </value>
                <value>
                    <fullName>OE Kit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Materials_Order_On_Standby__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Materials order is too early to place.</description>
        <label>Materials Order On Standby</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Materials_Order_placed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Materials Order has been placed</description>
        <label>Materials Order placed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Meeting_Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Meeting Cancelled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Meeting_Contact__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Meeting Contact</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meeting_Stage__c</fullName>
        <description>This field shows where the meeting is in the entry process.</description>
        <inlineHelpText>Change status to SUBMITTED when all fields have been entered and the meeting is ready for validation and submission to the OE Coordinator.</inlineHelpText>
        <label>Meeting Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DRAFT</fullName>
                    <default>true</default>
                    <label>DRAFT</label>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>SUBMITTED</fullName>
                </value>
                <value>
                    <fullName>Submitted - Rush</fullName>
                </value>
                <value>
                    <fullName>UPDATED</fullName>
                </value>
                <value>
                    <fullName>Updated - Rush</fullName>
                </value>
                <value>
                    <fullName>COMPLETE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Meeting_Status__c</fullName>
        <inlineHelpText>(LG06232014)Field is updated by workflows please do not change.</inlineHelpText>
        <label>Meeting Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>COMPLETED-CANCELLED</fullName>
                </value>
                <value>
                    <fullName>NEW REQUEST</fullName>
                    <default>true</default>
                    <label>NEW REQUEST</label>
                </value>
                <value>
                    <fullName>IN REVIEW</fullName>
                </value>
                <value>
                    <fullName>IN PROCESS – FACILITATOR BEING RECRUITED</fullName>
                </value>
                <value>
                    <fullName>IN PROCESS - FACILITATOR SECURED AND WAITING ON FEEDBACK</fullName>
                </value>
                <value>
                    <fullName>COMPLETED - FACILITATOR SECURED &amp;MEETING FEEDBACK RECEIVED</fullName>
                </value>
                <value>
                    <fullName>COMPLETED - MATERIALS DELIVERED</fullName>
                </value>
                <value>
                    <fullName>IN PROCESS – ORDER ON STANDBY</fullName>
                </value>
                <value>
                    <fullName>IN PROCESS- ORDER PLACED</fullName>
                </value>
                <value>
                    <fullName>IN PROCESS – FACILITATOR BEING RECRUITED &amp; ORDER on STANDBY</fullName>
                </value>
                <value>
                    <fullName>IN PROCESS -FACILITATOR SECURED  &amp; WAITING ON FEEDBACK &amp; ORDER ON STANDBY</fullName>
                </value>
                <value>
                    <fullName>IN PROCESS- FACILITATOR SECURED &amp; WAITING ON FEEDBACK &amp; ORDER PLACED</fullName>
                </value>
                <value>
                    <fullName>IN PROCESS -FACILITATOR BEING RECRUITED &amp; ORDER PLACED</fullName>
                </value>
                <value>
                    <fullName>IN PROCESS- FACILITATOR SECURED &amp; MATERIALS DELIVERED &amp; WAITING ON FEEDBACK</fullName>
                </value>
                <value>
                    <fullName>COMPLETED - FACILITATOR SECURED &amp; MATERIALS DELIVERED &amp; MEETING FEEDBACK RECEIVED</fullName>
                </value>
                <value>
                    <fullName>COMPLETED - UNABLE TO SECURE FACILITATOR &amp; MATERIALS DELIVERED</fullName>
                </value>
                <value>
                    <fullName>COMPLETED - UNABLE TO SECURE FACILITATOR</fullName>
                </value>
                <value>
                    <fullName>COMPLETED- FACILITATOR SECURED AND FEEDBACK NOT RECEIVED WITHIN 14 DAYS</fullName>
                </value>
                <value>
                    <fullName>Completed Cancelled - Override</fullName>
                </value>
                <value>
                    <fullName>OE KIT REQUEST ONLY</fullName>
                </value>
                <value>
                    <fullName>IN PROCESS -UNABLE TO SECURE FACILITATOR - ORDER PLACED</fullName>
                </value>
                <value>
                    <fullName>IN PROCESS - UNABLE TO SECURE FACILITATOR - ORDER ON STANDBY</fullName>
                </value>
                <value>
                    <fullName>COMPLETED- FACILITATOR SECURED &amp; MATERIALS DELIVERED &amp; FEEDBACK NOT RECEIVED WITHIN 14 DAYS</fullName>
                </value>
                <value>
                    <fullName>IN PROCESS - FACILITATOR SECURED &amp;  ORDER PLACED &amp; WAITING ON FEEDBACK</fullName>
                </value>
                <value>
                    <fullName>IN PROCESS -FACILITATOR BEING RECRUITED &amp; MATERIALS DELIVERED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RUSH__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Changes done under user story: PRDCRM - 27697</description>
        <inlineHelpText>Meeting Date less than or equal to 14 days from today</inlineHelpText>
        <label>RUSH</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reason_for_Update__c</fullName>
        <inlineHelpText>Select a reason for the change to assist the OE Coordinator.</inlineHelpText>
        <label>Reason for Update</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Meeting cancelled</fullName>
                </value>
                <value>
                    <fullName>Date Change</fullName>
                </value>
                <value>
                    <fullName>Session times change</fullName>
                </value>
                <value>
                    <fullName>Meeting address change</fullName>
                </value>
                <value>
                    <fullName>Delivery address change</fullName>
                </value>
                <value>
                    <fullName>Site contact name/ph# change</fullName>
                </value>
                <value>
                    <fullName>Facilitator Update</fullName>
                </value>
                <value>
                    <fullName>Materials Change</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>OE Kit Approved</fullName>
                </value>
                <value>
                    <fullName>OE Kit Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recruitment_of_Facilitator_Needed__c</fullName>
        <description>AM checks this if they will not be attending or if they don&apos;t already have a facilitator lined up.</description>
        <inlineHelpText>If Yes Open Enrollment Team will seek coverage.</inlineHelpText>
        <label>Facilitator Needs to be Recruited</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>User checks box when meeting is ready for processing by OE</description>
        <inlineHelpText>Check this box when the meeting is ready for processing.</inlineHelpText>
        <label>Submit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unable_to_secure_facilitator__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This box is checked when recruitment of a facilitator was unsuccessful</description>
        <label>Unable to secure facilitator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Waiting_on_Feedback__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Facilitator Feedback has not been received</description>
        <label>Waiting on Facilitator Feedback</label>
        <type>Checkbox</type>
    </fields>
    <label>Open Enrollment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Enrollment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OpenEnrollmentStageStatusTest.cls
/*************************************************************************************
Version     : 1.0 
@Author     : Mehaboob
@description :Test class for class OpenEnrollmentTriggerAction
@comment     : Created this class as part of Story PRDCRM-45610 and 43212
Created On : 10/30/2019
*************************************************************************************/
@isTest
private class OpenEnrollmentStageStatusTest{

@isTest
static void testInsertOrUpdateOE(){
       Test.setMock(HttpCalloutMock.class, TravelResponseServiceTest.getDefaultBingGeocodeMock());
          Id contactFacRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Facilitator Contact').getRecordTypeId();
         
         //Insert account
         List<Account> accountList = new List<Account>();
         accountList =TestDataFactory.createAccountSICList(1,'newaccount','CA street','CA','CA State','12345','US','CAA');
         insert accountList; 
         
        //Insert Account records
        List<Account> accRec = new List<Account>();
        Account accOeRec = new Account();
        accOeRec.Name = 'Open Enrollment';
        accOeRec.Anthem_Entity__c = 'National Accounts';
        accOeRec.Region__c = 'Central';
        accRec.add(accOeRec);
        insert accRec;
         
        List<Contact> contactList=new List<Contact>();
        contactList = TestDataFactory.createContact(1,'test','Test4',accRec[0],contactFacRecTypeId,'OE Coordinator','Central','test@test.com',true,0,0);
        insert contactList;
        
        List<Open_Enrollment_Meetings__c> oemeetingRec = new List<Open_Enrollment_Meetings__c>();
        oemeetingRec = TestDataFactory.createOpenEnrollmentMeeting(1,'Test123',accountList[0],'Georgia',contactList[0],UtilConstants.Plan_Type,'Commercial Medical','Yes','Test Performance comment','Renewal - Growth Opportunity','Sole Carrier','Test tally fields','3534353453',UtilConstants.Dress_Code_for_Event);
        insert oemeetingRec;
        
        List<SFDC_Volunteer_Event__c> oeRecList = new List<SFDC_Volunteer_Event__c>();
        oeRecList = TestDataFactory.createOpenEnrollment(1,'StageStatusOE',oemeetingRec[0],'No',FALSE,'321 N Clark','Chicago','IL','60654','12:00 AM','12:30 AM',System.Today(),'No',UtilConstants.MEETING_TYPE_OE,100,true,'DRAFT','Yes',41.8882434,-87.6328535,true,false,false,accRec[0],'New Request',contactList[0]);
        
        insert oeRecList;
        
       
       List<SFDC_Volunteer_Event__c> oeList=[select id,Name,Meeting_Stage__c,Meeting_Status__c,Submit__c,Meeting_Cancelled__c,Materials_Needed__c,Meeting_Contact__c,Contact_Phone_Number__c,Recruitment_of_Facilitator_Needed__c,RUSH__c from SFDC_Volunteer_Event__c where Name=:'StageStatusOE0' limit 1];
      
       oeList[0].Meeting_Cancelled__c=true;
       oeList[0].Submit__c=true;
       oeList[0].Materials_Needed__c='No Promo or Collateral Needed';
       oeList[0].Meeting_Contact__c='Test contact user';
       oeList[0].Contact_Phone_Number__c='1234567890';
       oeList[0].Recruitment_of_Facilitator_Needed__c='No';
       
       update oeList;
       
       oeList[0].Reason_for_Update__c='Date Change';
       oeList[0].Date__c=System.Today()-15;
       
       update oeList;
       
       oeList[0].Reason_for_Update__c='Session times change';
       update oeList;
       
       oeList[0].Recruitment_of_Facilitator_Needed__c='Yes';
       oeList[0].Materials_Needed__c='No Promo or Collateral Needed';
       oeList[0].Facilitator_Being_Recruited__c=false;
       oeList[0].Facilitator_Secured__c=true;
       oeList[0].Waiting_on_Feedback__c=false;
       oeList[0].Feedback_Not_Received_Within_14_Days__c=false;
       oeList[0].Facilitator_Feedback_Received__c=true;
       oeList[0].Unable_to_secure_facilitator__c=false;
       oeList[0].Submit__c=true;
       oeList[0].Materials_Order_On_Standby__c=false;
       oeList[0].Materials_Order_placed__c=false;
       oeList[0].Materials_Delivered__c=false;
       oeList[0].Meeting_Cancelled__c=false;
       
       update oeList;
       
       oeList[0].Recruitment_of_Facilitator_Needed__c='Yes';
       oeList[0].Materials_Needed__c='No Promo or Collateral Needed';
       oeList[0].Facilitator_Being_Recruited__c=false;
       oeList[0].Facilitator_Secured__c=true;
       oeList[0].Waiting_on_Feedback__c=false;
       oeList[0].Feedback_Not_Received_Within_14_Days__c=true;
       oeList[0].Facilitator_Feedback_Received__c=false;
       oeList[0].Unable_to_secure_facilitator__c=false;
       oeList[0].Submit__c=true;
       oeList[0].Materials_Order_On_Standby__c=false;
       oeList[0].Materials_Order_placed__c=false;
       oeList[0].Materials_Delivered__c=false;
       oeList[0].Meeting_Cancelled__c=false;
       
       update oeList;
       
       oeList[0].Recruitment_of_Facilitator_Needed__c='Yes';
       oeList[0].Materials_Needed__c='No Promo or Collateral Needed';
       oeList[0].Facilitator_Being_Recruited__c=false;
       oeList[0].Facilitator_Secured__c=true;
       oeList[0].Waiting_on_Feedback__c=true;
       oeList[0].Feedback_Not_Received_Within_14_Days__c=false;
       oeList[0].Facilitator_Feedback_Received__c=false;
       oeList[0].Unable_to_secure_facilitator__c=false;
       oeList[0].Submit__c=true;
       oeList[0].Materials_Order_On_Standby__c=false;
       oeList[0].Materials_Order_placed__c=false;
       oeList[0].Materials_Delivered__c=false;
       oeList[0].Meeting_Cancelled__c=false;
       
       update oeList;
       
       oeList[0].Recruitment_of_Facilitator_Needed__c='Yes';
       oeList[0].Materials_Needed__c='No Promo or Collateral Needed';
       oeList[0].Facilitator_Being_Recruited__c=true;
       oeList[0].Submit__c=true;
       oeList[0].Facilitator_Secured__c=false;
       oeList[0].Unable_to_secure_facilitator__c=false;
       oeList[0].Waiting_on_Feedback__c=false;
       oeList[0].Feedback_Not_Received_Within_14_Days__c=false;
       oeList[0].Facilitator_Feedback_Received__c=false;
       oeList[0].Materials_Order_On_Standby__c=false;
       oeList[0].Materials_Order_placed__c=false;
       oeList[0].Materials_Delivered__c=false;
       oeList[0].Meeting_Cancelled__c=false;
       
       update oeList;
      
     /* oeList[0].Date__c=System.TODAY() - 10;
       oeList[0].Meeting_Stage__c='SUBMITTED';
       
       update oeList;
       System.debug('stage is 10--->'+oeList[0].Meeting_Stage__c+'  Status is---->'+oeList[0].Meeting_Status__c);
     */
     
       oeList[0].Recruitment_of_Facilitator_Needed__c='Yes';
       oeList[0].Materials_Needed__c='Promo only needed ';
       oeList[0].Facilitator_Being_Recruited__c=false;
       oeList[0].Unable_to_secure_facilitator__c=true;
       oeList[0].Materials_Order_On_Standby__c=false;
       oeList[0].Materials_Order_placed__c=true;
       oeList[0].Materials_Delivered__c=true;
       oeList[0].Submit__c=true;
     
       update oeList;
       
       oeList[0].Recruitment_of_Facilitator_Needed__c='Yes';
       oeList[0].Materials_Needed__c='Promo only needed';
       oeList[0].Facilitator_Being_Recruited__c=false;
       oeList[0].Unable_to_secure_facilitator__c=true;
       oeList[0].Materials_Order_On_Standby__c=false;
       oeList[0].Materials_Order_placed__c=true;
       oeList[0].Materials_Delivered__c=false;
       oeList[0].Submit__c=true;
       
       update oeList;
       
       oeList[0].Recruitment_of_Facilitator_Needed__c='Yes';
       oeList[0].Materials_Needed__c='Promo only needed';
       oeList[0].Facilitator_Being_Recruited__c=false;
       oeList[0].Facilitator_Secured__c=true;
       oeList[0].Unable_to_secure_facilitator__c=false;
       oeList[0].Waiting_on_Feedback__c=false;
       oeList[0].Feedback_Not_Received_Within_14_Days__c=false;
       oeList[0].Facilitator_Feedback_Received__c=true;
       oeList[0].Materials_Order_On_Standby__c=false;
       oeList[0].Materials_Order_placed__c=true;
       oeList[0].Materials_Delivered__c=true;
       oeList[0].Submit__c=true;
       
       update oeList;
       
       oeList[0].Recruitment_of_Facilitator_Needed__c='Yes';
       oeList[0].Materials_Needed__c='Promo only needed';
       oeList[0].Facilitator_Being_Recruited__c=false;
       oeList[0].Facilitator_Secured__c=true;
       oeList[0].Waiting_on_Feedback__c=false;
       oeList[0].Feedback_Not_Received_Within_14_Days__c=true;
       oeList[0].Materials_Order_placed__c=true;
       oeList[0].Materials_Delivered__c=true;
       oeList[0].Submit__c=true;
       oeList[0].Facilitator_Feedback_Received__c=false;
       
       update oeList;
       
       oeList[0].Recruitment_of_Facilitator_Needed__c='Yes';
       oeList[0].Materials_Needed__c='Promo only needed';
       oeList[0].Facilitator_Being_Recruited__c=false;
       oeList[0].Facilitator_Secured__c=true;
       oeList[0].Unable_to_secure_facilitator__c=false;
       oeList[0].Waiting_on_Feedback__c=true;
       oeList[0].Feedback_Not_Received_Within_14_Days__c=false;
       oeList[0].Facilitator_Feedback_Received__c=false;
       oeList[0].Materials_Order_On_Standby__c=false;
       oeList[0].Materials_Order_placed__c=true;
       oeList[0].Materials_Delivered__c=true;
       oeList[0].Meeting_Cancelled__c=false;
       oeList[0].Submit__c=true;
       
       update oeList;
       
       oeList[0].Recruitment_of_Facilitator_Needed__c='Yes';
       oeList[0].Materials_Needed__c='Promo only needed';
       oeList[0].Facilitator_Being_Recruited__c=false;
       oeList[0].Facilitator_Secured__c=false;
       oeList[0].Unable_to_secure_facilitator__c=true;
       oeList[0].Waiting_on_Feedback__c=false;
       oeList[0].Feedback_Not_Received_Within_14_Days__c=false;
       oeList[0].Facilitator_Feedback_Received__c=false;
       oeList[0].Materials_Order_On_Standby__c=true;
       oeList[0].Materials_Order_placed__c=false;
       oeList[0].Submit__c=true;
       oeList[0].Materials_Delivered__c=false;
       oeList[0].Meeting_Cancelled__c=false;
      
       update oeList;
       
      /* IN PROCESS - FACILITATOR SECURED & ORDER PLACED & WAITING ON FEEDBACK
      
       oeList[0].Recruitment_of_Facilitator_Needed__c='Yes';
       oeList[0].Materials_Needed__c='Promo only needed';
       oeList[0].Facilitator_Being_Recruited__c=false;
       oeList[0].Facilitator_Secured__c=true;
       oeList[0].Waiting_on_Feedback__c=true;
       oeList[0].Materials_Order_On_Standby__c=false;
       oeList[0].Materials_Order_placed__c=true;
       oeList[0].Submit__c=true;
       oeList[0].Materials_Delivered__c=false;
       
       update oeList;
       System.debug('stage is 17--->'+oeList[0].Meeting_Stage__c+'  Status is---->'+oeList[0].Meeting_Status__c);
       */
       
       oeList[0].Recruitment_of_Facilitator_Needed__c='Yes';
       oeList[0].Materials_Needed__c='No Promo or Collateral Needed';
       oeList[0].Facilitator_Being_Recruited__c=false;
       oeList[0].Facilitator_Secured__c=false;
       oeList[0].Unable_to_secure_facilitator__c=true;
       oeList[0].Waiting_on_Feedback__c=false;
       oeList[0].Feedback_Not_Received_Within_14_Days__c=false;
       oeList[0].Facilitator_Feedback_Received__c=false;
       oeList[0].Materials_Order_On_Standby__c=false;
       oeList[0].Materials_Order_placed__c=false;
       oeList[0].Materials_Delivered__c=false;
       oeList[0].Meeting_Cancelled__c=true;
       oeList[0].Submit__c=true;
       
       update oeList;
       
       oeList[0].Recruitment_of_Facilitator_Needed__c='Yes';
       oeList[0].Materials_Needed__c='Promo only needed';
       oeList[0].Facilitator_Being_Recruited__c=true;
       oeList[0].Facilitator_Secured__c=false;
       oeList[0].Unable_to_secure_facilitator__c=false;
       oeList[0].Waiting_on_Feedback__c=false;
       oeList[0].Feedback_Not_Received_Within_14_Days__c=false;
       oeList[0].Facilitator_Feedback_Received__c=false;
       oeList[0].Materials_Order_On_Standby__c=true;
       oeList[0].Materials_Order_placed__c=false;
       oeList[0].Materials_Delivered__c=false;
       oeList[0].Meeting_Cancelled__c=false;
       oeList[0].Submit__c=true;
       
       update oeList;
       
       oeList[0].Recruitment_of_Facilitator_Needed__c='Yes';
       oeList[0].Materials_Needed__c='Promo only needed';
       oeList[0].Facilitator_Being_Recruited__c=true;
       oeList[0].Materials_Order_placed__c=true;
       oeList[0].Materials_Delivered__c=true;
       oeList[0].Materials_Order_On_Standby__c=false;
       oeList[0].Submit__c=true;    
       
       update oeList;
       
       oeList[0].Recruitment_of_Facilitator_Needed__c='Yes';
       oeList[0].Materials_Needed__c='Promo only needed';
       oeList[0].Facilitator_Being_Recruited__c=true;
       oeList[0].Materials_Order_On_Standby__c=false;
       oeList[0].Materials_Order_placed__c=true;
       oeList[0].Materials_Delivered__c=false;
       oeList[0].Submit__c=true;
       
       update oeList;
       
       oeList[0].Recruitment_of_Facilitator_Needed__c='Yes';
       oeList[0].Materials_Needed__c='Promo only needed';
       oeList[0].Facilitator_Being_Recruited__c=false;
       oeList[0].Facilitator_Secured__c=true;
       oeList[0].Unable_to_secure_facilitator__c=false;
       oeList[0].Waiting_on_Feedback__c=true;
       oeList[0].Feedback_Not_Received_Within_14_Days__c=false;
       oeList[0].Facilitator_Feedback_Received__c=false;
       oeList[0].Materials_Order_On_Standby__c=true;
       oeList[0].Materials_Order_placed__c=false;
       oeList[0].Materials_Delivered__c=false;
       oeList[0].Meeting_Cancelled__c=false;
       oeList[0].Submit__c=true;
       
       
       update oeList;
       
       oeList[0].Recruitment_of_Facilitator_Needed__c='No';
       oeList[0].Materials_Needed__c='Promo only needed';
       oeList[0].Facilitator_Being_Recruited__c=false;
       oeList[0].Facilitator_Secured__c=false;
       oeList[0].Unable_to_secure_facilitator__c=false;
       oeList[0].Waiting_on_Feedback__c=false;
       oeList[0].Feedback_Not_Received_Within_14_Days__c=false;
       oeList[0].Facilitator_Feedback_Received__c=false;
       oeList[0].Materials_Order_On_Standby__c=true;
       oeList[0].Materials_Order_placed__c=false;
       oeList[0].Materials_Delivered__c=false;
       oeList[0].Meeting_Cancelled__c=false;
       oeList[0].Submit__c=true;
       
       update oeList;
       
       oeList[0].Recruitment_of_Facilitator_Needed__c='No';
       oeList[0].Materials_Needed__c='Promo only needed';
       oeList[0].Materials_Order_placed__c=true;
       oeList[0].Materials_Delivered__c=true;
       oeList[0].Materials_Order_On_Standby__c=false;
       oeList[0].Submit__c=true;
       
       update oeList;
      
       oeList[0].Recruitment_of_Facilitator_Needed__c='No';
       oeList[0].Materials_Needed__c='Promo only needed';
       oeList[0].Materials_Order_placed__c=true;
       oeList[0].Materials_Delivered__c=false;
       oeList[0].Materials_Order_On_Standby__c=false;
       oeList[0].Submit__c=true;
       
       update oeList;
       
       List<SFDC_Volunteer_Event__c> openEnrollmentList=[select id,Name,Meeting_Stage__c,Materials_Delivered__c,Meeting_Status__c,Submit__c,Meeting_Cancelled__c,Materials_Needed__c,Meeting_Contact__c,Contact_Phone_Number__c,Recruitment_of_Facilitator_Needed__c,RUSH__c from SFDC_Volunteer_Event__c limit 1];
      System.assertEquals(openEnrollmentList[0].Meeting_Stage__c,'In Process' ,'Stage of Open Enrollment ');
      System.assertEquals(openEnrollmentList[0].Meeting_Status__c,'IN PROCESS- ORDER PLACED' ,'Status of Open Enrollment ');
      System.assertEquals(openEnrollmentList[0].RUSH__c,false,'Rush of Open Enrollment ');
       
   }
}