objects/PG_Catalog_Item__c.object
<CustomObject>
    <description>Represents the Catalog/Library of Anthem’s Performance Guarantees. Each has a unique configuration. This list of records and their configuration is maintained by the PG Support Team. These are associated to a Customer via creation of ‘PG Line Item’ record(s). Created per PRDCRM-51224.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Broad_Contract_Category__c</fullName>
        <label>Broad Contract Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Care Management</fullName>
                </value>
                <value>
                    <fullName>Case Management</fullName>
                </value>
                <value>
                    <fullName>Case Management JAA Health Link</fullName>
                </value>
                <value>
                    <fullName>Cost of Care / Care Management</fullName>
                </value>
                <value>
                    <fullName>Integrated Imaging</fullName>
                </value>
                <value>
                    <fullName>Network</fullName>
                </value>
                <value>
                    <fullName>Operations</fullName>
                </value>
                <value>
                    <fullName>Pharmacy</fullName>
                </value>
                <value>
                    <fullName>Pharmacy Plus</fullName>
                </value>
                <value>
                    <fullName>Privacy</fullName>
                </value>
                <value>
                    <fullName>Stop Loss</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PG_Type__c</fullName>
        <label>PG Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Back Pocket Standard</fullName>
                </value>
                <value>
                    <fullName>Non Standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Performance_Category__c</fullName>
        <label>Performance Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Implementation</fullName>
                </value>
                <value>
                    <fullName>Implementation Survey</fullName>
                </value>
                <value>
                    <fullName>Claims Timeliness (14 Calendar Days)</fullName>
                </value>
                <value>
                    <fullName>Claims Timeliness (30 Calendar Days)</fullName>
                </value>
                <value>
                    <fullName>Claims Financial Accuracy</fullName>
                </value>
                <value>
                    <fullName>Claims Accuracy</fullName>
                </value>
                <value>
                    <fullName>Open Enrollment ID Card Issuance</fullName>
                </value>
                <value>
                    <fullName>Processing of Ongoing Eligibility Information</fullName>
                </value>
                <value>
                    <fullName>Ongoing ID Card Issuance</fullName>
                </value>
                <value>
                    <fullName>Average Speed to Answer</fullName>
                </value>
                <value>
                    <fullName>Call Abandonment Rate</fullName>
                </value>
                <value>
                    <fullName>First Call Resolution</fullName>
                </value>
                <value>
                    <fullName>Member Satisfaction (NPS)</fullName>
                </value>
                <value>
                    <fullName>Member Satisfaction (Service Skills)</fullName>
                </value>
                <value>
                    <fullName>Management Reports</fullName>
                </value>
                <value>
                    <fullName>Account Management/Client Team Satisfaction</fullName>
                </value>
                <value>
                    <fullName>Appeals</fullName>
                </value>
                <value>
                    <fullName>Website Availability</fullName>
                </value>
                <value>
                    <fullName>Network Provider Discount</fullName>
                </value>
                <value>
                    <fullName>Total Provider Discount</fullName>
                </value>
                <value>
                    <fullName>Network Alerts</fullName>
                </value>
                <value>
                    <fullName>Provider Accessibility</fullName>
                </value>
                <value>
                    <fullName>Condition Care Enrollment Rate</fullName>
                </value>
                <value>
                    <fullName>Condition Care Engagement Rate</fullName>
                </value>
                <value>
                    <fullName>Condition Care  Member Satisfaction</fullName>
                </value>
                <value>
                    <fullName>Heart Failure ACE Inhibitors/ARB</fullName>
                </value>
                <value>
                    <fullName>Diabetes Annual Hemoglobin A1c (HbA1c) Testing</fullName>
                </value>
                <value>
                    <fullName>Persistent Asthma Prescription Drug Dispense</fullName>
                </value>
                <value>
                    <fullName>CAD (Statin Medications)</fullName>
                </value>
                <value>
                    <fullName>Clinical Health and Wellness Foundational Package Return on Investment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PG Catalog Item</label>
    <nameField>
        <displayFormat>PGCAT-{0000}</displayFormat>
        <label>PG Catalog Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PG Catalog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CatalogController.cls
/**
@author : Ravideep (XMEN)
@createdDate 03/06/2020
@description This is the server side class for metricFilter lightning web component
*/
public with sharing class CatalogController {
    static Integer PAGE_SIZE = Integer.valueOf(system.label.MetricListPageSize);
    public class Filters {
        @AuraEnabled
        public String searchKey { get; set; }
        @AuraEnabled
        public String[] pgtypes { get; set; }
        @AuraEnabled
        public String[] contractcategories { get; set; }
        @AuraEnabled
        public String[] performancecategories { get; set; }
    }
   
    @AuraEnabled(cacheable=true)
    public static PagedResult getPGCatalogItems(Filters filters, Integer pageNumber) {
        String key, whereClause = '';
        String[] pgtypes, contractcategories, performancecategories, criteria = new List<String>{};
        system.debug('filters--->' + filters);
        
        if (filters != null) {
            pgtypes = filters.pgtypes;
            contractcategories = filters.contractcategories;
            performancecategories = filters.performancecategories;
            if (!String.isEmpty(filters.searchKey)) {
                key = '%' + filters.searchKey + '%';
                criteria.add('(Performance_Category__c LIKE :key OR Broad_Contract_Category__c LIKE :key)');
            }
            
            if (filters.pgtypes != null && !filters.pgtypes.isEmpty()) {
                pgtypes = filters.pgtypes;
                criteria.add('PG_Type__c IN :pgtypes');
            }
            if (filters.performancecategories != null && !filters.performancecategories.isEmpty()) {
                performancecategories = filters.performancecategories;
                criteria.add('Performance_Category__c IN :performancecategories');
            }
            if (filters.contractcategories != null && !filters.contractcategories.isEmpty()) {
                contractcategories = filters.contractcategories;
                criteria.add('Broad_Contract_Category__c IN :contractcategories');
            }
            if (criteria.size() > 0) {
                system.debug('criteria--> ' + criteria);
                whereClause = 'AND ' + String.join(criteria, ' AND ');
            }
        }
        Integer pageSize = CatalogController.PAGE_SIZE;
        Integer offset = (pageNumber - 1) * pageSize;
        PagedResult result = new PagedResult();
        result.pageSize = pageSize;
        result.pageNumber = pageNumber;
        system.debug('whereClause--> ' + whereClause);
        
        try{
        result.totalItemCount = Database.countQuery(
            'SELECT count() FROM PG_Catalog_Item__c WHERE active__c = true ' + whereClause  
        );
        } 
        catch(Exception e) {
             System.debug('Exception caught: ' + e.getMessage()); 
        }
        
        
        try{
        result.records = Database.query(
            'SELECT Id,active__c , Name, PG_Type__c, Performance_Category__c,Broad_Contract_Category__c FROM PG_Catalog_Item__c WHERE active__c = true ' +
            whereClause + 
            ' WITH SECURITY_ENFORCED' +
            ' ORDER BY sequence__c LIMIT :pageSize OFFSET :offset'
        );
        } 
        catch(Exception e) {
             System.debug('Exception caught: ' + e.getMessage()); 
        }
        system.debug('result.records--->' + result.records);
        return result;
    }
}