objects/PG_Catalog_Item__c.object
<CustomObject>
    <description>Represents the Catalog/Library of Anthem’s Performance Guarantees. Each has a unique configuration. This list of records and their configuration is maintained by the PG Support Team. These are associated to a Customer via creation of ‘PG Line Item’ record(s). Created per PRDCRM-51224.</description>
    <label>PG Catalog Item</label>
    <nameField>
        <displayFormat>PGCAT-{0000}</displayFormat>
        <label>PG Catalog Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PG Catalog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PG_Metric__c.object
<CustomObject>
    <description>Represents an individual Performance Guarantee which is offered to the Client. There will be often be multiple per each PG Request. Each record is an instance of a the custom object ‘PG Catalog Item’. Created per PRDCRM-51221.</description>
    <fields>
        <fullName>Measurement_Period__c</fullName>
        <label>Measurement Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Annual beginning with the start of the fourth month of the initial Agreement Period</fullName>
                </value>
                <value>
                    <fullName>Annual plus 12 months of Claims Runout</fullName>
                </value>
                <value>
                    <fullName>Defined in Implementation Plan</fullName>
                </value>
                <value>
                    <fullName>Employer&apos;s effective date</fullName>
                </value>
                <value>
                    <fullName>Commencing on data specified and ending 18 months thereafter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PG_Catalog_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PG Catalog Item</label>
        <referenceTo>PG_Catalog_Item__c</referenceTo>
        <relationshipName>PG_Metric</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PG_Request_ID__c</fullName>
        <label>PG Request ID</label>
        <referenceTo>PG_Request__c</referenceTo>
        <relationshipName>PG_Metric</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <label>Reporting Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Semi Annual</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>60 calendar days following the end of the implementation plan</fullName>
                </value>
                <value>
                    <fullName>60 calendar days following Anthem&apos;s receipt of the survey</fullName>
                </value>
                <value>
                    <fullName>60 calendar days following the Employer&apos;s effective date</fullName>
                </value>
                <value>
                    <fullName>Initial Report to be provided 6 months after the Measurement Period.  Final Report at the conclusion of the 12 month Claims Runout Period as identified in the Measurement Period</fullName>
                </value>
                <value>
                    <fullName>Within 90 days following the end of the Measurement Period</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Bi Annual</fullName>
                    <isActive>false</isActive>
                    <label>Bi Annual</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Pending SME Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Pending Legal Review</fullName>
                </value>
                <value>
                    <fullName>Approved for Catalog Addition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tiering_Result_and_Penalty_Option__c</fullName>
        <label>Tiering Result and Penalty Option</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Option 1 (No Tiering)</fullName>
                </value>
                <value>
                    <fullName>Option 2 (Standard Tiering)</fullName>
                </value>
                <value>
                    <fullName>Option 3 (Custom Tiering)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PG Metric</label>
    <nameField>
        <displayFormat>PGMETR-{0000}</displayFormat>
        <label>PG Metric ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PG Metric</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CreateMetricRecord.cls
/**
@author : Smita (XMEN)
@createdDate 03/12/2020
@description This is the server side class for metricCard lightning web component
*/



public class CreateMetricRecord {

@AuraEnabled


public static PG_Metric__c createMetric(String id,String measurementPeriod,String reportingPeriod,String pgReqId,String tieringValue) {
    
  
   PG_Metric__c  metric=new PG_Metric__c();
    
    try{
    
       
        metric.PG_Request_ID__c=pgReqId;
        metric.Status__c='Initiated';
        metric.PG_Catalog_Item__c=id;
        System.debug('MP'+measurementPeriod);
        metric.Measurement_Period__c=measurementPeriod;
        metric.Reporting_Period__c=reportingPeriod;
        metric.Tiering_Result_and_Penalty_Option__c=tieringValue;
        System.debug('MP'+metric.Measurement_Period__c);
        insert metric;
        
     }
    
    
    catch(DmlException e) {
        System.debug('The following exception has occurred: ' + e.getMessage());
        throw new AuraHandledException('');
       
    }
    
    return metric;
}
}