objects/PG_Catalog_Item__c.object
<CustomObject>
    <description>Represents the Catalog/Library of Anthem’s Performance Guarantees. Each has a unique configuration. This list of records and their configuration is maintained by the PG Support Team. These are associated to a Customer via creation of ‘PG Line Item’ record(s). Created per PRDCRM-51224.</description>
    <label>PG Catalog Item</label>
    <nameField>
        <displayFormat>PGCAT-{0000}</displayFormat>
        <label>PG Catalog Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PG Catalog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PG_Metric__c.object
<CustomObject>
    <description>Represents an individual Performance Guarantee which is offered to the Client. There will be often be multiple per each PG Request. Each record is an instance of a the custom object ‘PG Catalog Item’. Created per PRDCRM-51221.</description>
    <fields>
        <fullName>Measurement_Period__c</fullName>
        <label>Measurement Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Annual beginning with the start of the fourth month of the initial Agreement Period</fullName>
                </value>
                <value>
                    <fullName>Annual plus 12 months of Claims Runout</fullName>
                </value>
                <value>
                    <fullName>Defined in Implementation Plan</fullName>
                </value>
                <value>
                    <fullName>Employer&apos;s effective date</fullName>
                </value>
                <value>
                    <fullName>Commencing on data specified and ending 18 months thereafter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PG_Catalog_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PG Catalog Item</label>
        <referenceTo>PG_Catalog_Item__c</referenceTo>
        <relationshipName>PG_Metric</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <label>Reporting Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Semi Annual</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>60 calendar days following the end of the implementation plan</fullName>
                </value>
                <value>
                    <fullName>60 calendar days following Anthem&apos;s receipt of the survey</fullName>
                </value>
                <value>
                    <fullName>60 calendar days following the Employer&apos;s effective date</fullName>
                </value>
                <value>
                    <fullName>Initial Report to be provided 6 months after the Measurement Period.  Final Report at the conclusion of the 12 month Claims Runout Period as identified in the Measurement Period</fullName>
                </value>
                <value>
                    <fullName>Within 90 days following the end of the Measurement Period</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Bi Annual</fullName>
                    <isActive>false</isActive>
                    <label>Bi Annual</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Pending SME Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Pending Legal Review</fullName>
                </value>
                <value>
                    <fullName>Approved for Catalog Addition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PG Metric</label>
    <nameField>
        <displayFormat>PGMETR-{0000}</displayFormat>
        <label>PG Metric ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PG Metric</pluralLabel>
    <recordTypes>
        <fullName>Implementation</fullName>
        <active>true</active>
        <label>Implementation</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PG_Request__c.object
<CustomObject>
    <description>Represents the overall Performance Guarantee Request. There will often be a single record per New Business or Renewal Opportunity, but there could be multiple (e.g. when PGs offered vary greatly by Group/Case number). Created per PRDCRM-50558</description>
    <label>PG Request</label>
    <nameField>
        <displayFormat>PGREQ-{0000}</displayFormat>
        <label>PG Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PG Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateMetricRecordTest.cls
/**
@author : Smita (XMEN)
@createdDate : 03/12/2020
@description This is test class for server side 'CreateMetricRecord' Class
*/
@isTest
public class CreateMetricRecordTest{
    
/*******************************************************************************************************
* @description: Sets up test data
* @param: null 
* @return: Doesn't return anything
*/  
    @testSetup
    public static void testSetUpMethod(){
          
        PG_Request__c pgRequest = new PG_Request__c();
        pgRequest=TestDataFactory.createPGRequestItem();
        insert pgRequest;
            
            PG_Catalog_Item__c pgitem = new PG_Catalog_Item__c();
        pgitem = TestDataFactory.createPGCatalogItem(staticVariableClass.STANDARD,staticVariableClass.IMPLEMENTATION,staticVariableClass.OPERATIONS);
        insert pgitem; 
        
        PG_Metric__c  pgMetric = new PG_Metric__c  ();
        //createMetricRecord creMetric=new createMetricRecord ();
        pgMetric = createMetricRecord.createMetric(pgitem.ID,'Annual','Annual',pgRequest.ID,'Option 1 (No Tiering)');
        
    }
    
/*******************************************************************************************************
* @description test method for CatalogController unit tests
* @param null 
* @return Doesn't return anything
*/  
    @isTest
    public static void testPGCatalogItems(){
        List<PG_Metric__c  > pgMetric = new List<PG_Metric__c  >([select id,Measurement_Period__c,status__c,Reporting_Period__c from PG_Metric__c  limit 1]);
        system.debug('pgCatalogItemList---> '+ pgMetric );
        
        System.assertEquals(pgMetric[0] .Measurement_Period__c ,'Annual', 'Measurement Period is Equal');
        System.assertEquals(pgMetric[0] .Status__c ,'Initiated', 'Status is Equal');
        System.assertEquals(pgMetric[0] .Reporting_Period__c,'Annual', 'Reporting Period is Equal');
        
        }
}