objects/PG_Catalog_Item__c.object
<CustomObject>
    <description>Represents the Catalog/Library of Anthem’s Performance Guarantees. Each has a unique configuration. This list of records and their configuration is maintained by the PG Support Team. These are associated to a Customer via creation of ‘PG Line Item’ record(s). Created per PRDCRM-51224.</description>
    <fields>
        <fullName>Broad_Contract_Category__c</fullName>
        <label>Broad Contract Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Care Management</fullName>
                </value>
                <value>
                    <fullName>Case Management</fullName>
                </value>
                <value>
                    <fullName>Case Management JAA Health Link</fullName>
                </value>
                <value>
                    <fullName>Cost of Care / Care Management</fullName>
                </value>
                <value>
                    <fullName>Integrated Imaging</fullName>
                </value>
                <value>
                    <fullName>Network</fullName>
                </value>
                <value>
                    <fullName>Operations</fullName>
                </value>
                <value>
                    <fullName>Pharmacy</fullName>
                </value>
                <value>
                    <fullName>Pharmacy Plus</fullName>
                </value>
                <value>
                    <fullName>Privacy</fullName>
                </value>
                <value>
                    <fullName>Stop Loss</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PG_Type__c</fullName>
        <label>PG Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Back Pocket Standard</fullName>
                </value>
                <value>
                    <fullName>Non Standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Performance_Category__c</fullName>
        <label>Performance Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Implementation</fullName>
                </value>
                <value>
                    <fullName>Implementation Survey</fullName>
                </value>
                <value>
                    <fullName>Claims Timeliness (14 Calendar Days)</fullName>
                </value>
                <value>
                    <fullName>Claims Timeliness (30 Calendar Days)</fullName>
                </value>
                <value>
                    <fullName>Claims Financial Accuracy</fullName>
                </value>
                <value>
                    <fullName>Claims Accuracy</fullName>
                </value>
                <value>
                    <fullName>Open Enrollment ID Card Issuance</fullName>
                </value>
                <value>
                    <fullName>Processing of Ongoing Eligibility Information</fullName>
                </value>
                <value>
                    <fullName>Ongoing ID Card Issuance</fullName>
                </value>
                <value>
                    <fullName>Average Speed to Answer</fullName>
                </value>
                <value>
                    <fullName>Call Abandonment Rate</fullName>
                </value>
                <value>
                    <fullName>First Call Resolution</fullName>
                </value>
                <value>
                    <fullName>Member Satisfaction (NPS)</fullName>
                </value>
                <value>
                    <fullName>Member Satisfaction (Service Skills)</fullName>
                </value>
                <value>
                    <fullName>Management Reports</fullName>
                </value>
                <value>
                    <fullName>Account Management/Client Team Satisfaction</fullName>
                </value>
                <value>
                    <fullName>Appeals</fullName>
                </value>
                <value>
                    <fullName>Website Availability</fullName>
                </value>
                <value>
                    <fullName>Network Provider Discount</fullName>
                </value>
                <value>
                    <fullName>Total Provider Discount</fullName>
                </value>
                <value>
                    <fullName>Network Alerts</fullName>
                </value>
                <value>
                    <fullName>Provider Accessibility</fullName>
                </value>
                <value>
                    <fullName>Condition Care Enrollment Rate</fullName>
                </value>
                <value>
                    <fullName>Condition Care Engagement Rate</fullName>
                </value>
                <value>
                    <fullName>Condition Care  Member Satisfaction</fullName>
                </value>
                <value>
                    <fullName>Heart Failure ACE Inhibitors/ARB</fullName>
                </value>
                <value>
                    <fullName>Diabetes Annual Hemoglobin A1c (HbA1c) Testing</fullName>
                </value>
                <value>
                    <fullName>Persistent Asthma Prescription Drug Dispense</fullName>
                </value>
                <value>
                    <fullName>CAD (Statin Medications)</fullName>
                </value>
                <value>
                    <fullName>Clinical Health and Wellness Foundational Package Return on Investment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PG Catalog Item</label>
    <nameField>
        <displayFormat>PGCAT-{0000}</displayFormat>
        <label>PG Catalog Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PG Catalog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CatalogControllerTest.cls
/**
@author : Ravideep (XMEN)
@createdDate : 03/06/200
@description This is test class for server side 'CatalogController' Class
*/
@isTest
public class CatalogControllerTest{
    
/*******************************************************************************************************
* @description: Sets up test data
* @param: null 
* @return: Doesn't return anything
*/  
    @testSetup
    public static void testSetUpMethod(){
          
        PG_Catalog_Item__c pgitem = new PG_Catalog_Item__c();
        pgitem = TestDataFactory.createPGCatalogItem(staticVariableClass.STANDARD,staticVariableClass.IMPLEMENTATION,staticVariableClass.OPERATIONS);
        insert pgitem;
    }
    
/*******************************************************************************************************
* @description test method for CatalogController unit tests
* @param null 
* @return Doesn't return anything
*/  
    @isTest
    public static void testPGCatalogItems(){
        List<PG_Catalog_Item__c> pgCatalogItemList = new List<PG_Catalog_Item__c>([select id,PG_Type__c,Performance_Category__c,Broad_Contract_Category__c from PG_Catalog_Item__c limit 1]);
        system.debug('pgCatalogItemList---> '+ pgCatalogItemList);
        
        CatalogController.Filters filter = new CatalogController.Filters();
        PagedResult PR = new PagedResult();
        
        if(pgCatalogItemList.size()>0){
            filter.searchKey = staticVariableClass.IMPLEMENTATION;    
            filter.pgtypes = new List<String>{pgCatalogItemList[0].PG_Type__c};
            filter.contractcategories = new List<String>{pgCatalogItemList[0].Broad_Contract_Category__c};
            filter.performancecategories = new List<String>{pgCatalogItemList[0].Performance_Category__c};
            test.startTest();
            PR = CatalogController.getPGCatalogItems(filter,Integer.valueOf(system.label.MetricListPageSize));
            }
            system.debug('PR--> ' + PR );
            system.assertEquals(1, PR.totalItemCount);
            
            test.stopTest();
    }
}