objects/Questionnaire_Implementation__c.object
<CustomObject>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Developer_Changes_how_do_you_track__c</fullName>
        <inlineHelpText>How do you keep track of and/or manage developer’s changes?</inlineHelpText>
        <label>Developer Changes (how do you track ?)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>How_Often__c</fullName>
        <description>How often do you encounter errors?</description>
        <label>How often do you encounter errors?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>How_are_metadata_components_being_dep__c</fullName>
        <inlineHelpText>How are metadata components being deployed currently?</inlineHelpText>
        <label>How are metadata components are deployed</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Change Sets</fullName>
                </value>
                <value>
                    <fullName>Ant Scripts</fullName>
                </value>
                <value>
                    <fullName>CI Server (Jenkins, Bamboo, CircleCI etc.)</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Other (Text Field - mandatory if none of the above are selected)</fullName>
                    <isActive>false</isActive>
                    <label>Other (Text Field - mandatory if none of the above are selected)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>How_long_does_it_take_for_pre_post_de__c</fullName>
        <inlineHelpText>How long does it take for pre/post deployment steps?</inlineHelpText>
        <label>Time for pre/post deployment steps ?</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>How_often_Data_Loader__c</fullName>
        <inlineHelpText>How often do you do data loading ?</inlineHelpText>
        <label>How often do you do data loading ?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_of_other_System__c</fullName>
        <inlineHelpText>Please specify the Version Control system used under Others</inlineHelpText>
        <label>Plz specify other (VC)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_of_time__c</fullName>
        <inlineHelpText>How often do you commit changes to version control?</inlineHelpText>
        <label>Changes committed to Version Control?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plz_specify_other_ALM__c</fullName>
        <inlineHelpText>Please specify the Project Management used under Others</inlineHelpText>
        <label>Plz specify other (ALM)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plz_specify_other_Metadata_components__c</fullName>
        <inlineHelpText>Please specify how metadata components being deployed currently if not mentioned above ?</inlineHelpText>
        <label>Plz specify other (Metadata components)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plz_specify_others__c</fullName>
        <inlineHelpText>Who are your primary SI Partners (if any)?</inlineHelpText>
        <label>Plz specify other (SI Partners)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_taken_for__c</fullName>
        <inlineHelpText>How much time does it take for a production deployment?</inlineHelpText>
        <label>Time taken for production deployment ?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Typically_how_many_records_do_you_mi__c</fullName>
        <inlineHelpText>Typically, how many records do you migrate per data load?</inlineHelpText>
        <label>No. records do you migrate per data load</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>What_are_the_pain_points_during_the_d__c</fullName>
        <inlineHelpText>What are the pain points during the deployment process?</inlineHelpText>
        <label>Pain point during Deployment process ?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>What_does_your_current_release_process__c</fullName>
        <inlineHelpText>What does your current release process look like? Please attach the files</inlineHelpText>
        <label>What does your current release process</label>
        <length>256</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>What_is_the_current_team_structure_w__c</fullName>
        <label>Current team structure w/  their roles</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>#Developers</fullName>
                </value>
                <value>
                    <fullName>#Admins</fullName>
                </value>
                <value>
                    <fullName>#Release Managers/Architects</fullName>
                </value>
                <value>
                    <fullName>Who are your primary SI Partners (if any)?</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>What_kind_of_testing_do_you_perform__c</fullName>
        <label>What kind of testing do you perform?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Apex only</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>Automation</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <isActive>false</isActive>
                    <label>None</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>X1_Any_ETL_tool_currently_being_used__c</fullName>
        <inlineHelpText>Any ETL tool currently being used?</inlineHelpText>
        <label>Any ETL tool currently being used?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X1_Which_Version_Control_System_is_used__c</fullName>
        <label>Which Version Control System is used ?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GIT</fullName>
                </value>
                <value>
                    <fullName>SVN</fullName>
                </value>
                <value>
                    <fullName>TFS</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>X2_Which_tool_is_used_for_Project_Manage__c</fullName>
        <inlineHelpText>Which tool is used for Project Management (ALM)?</inlineHelpText>
        <label>Which tool is used for ALM ?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>JIRA</fullName>
                </value>
                <value>
                    <fullName>Rally</fullName>
                </value>
                <value>
                    <fullName>HP ALM</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Demo Questionnaire</label>
    <nameField>
        <displayFormat>Quest{0}</displayFormat>
        <label>IQ- Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Implementation_Questionnaire_1_Test.cls
@isTest
private class Implementation_Questionnaire_1_Test{
    @testSetup
    static void setupTestData(){
        test.startTest();
        List<Questionnaire_Implementation__c> questionnaire_implementation_Obj = new List<Questionnaire_Implementation__c>{
            new Questionnaire_Implementation__c(CreatedDate = DateTime.now(),  LastModifiedDate = DateTime.now()    , Time_taken_for__c='30', Company_Name__c='Test', Email__c='test@test.com', What_kind_of_testing_do_you_perform__c='Apex only', What_does_your_current_release_process__c='Test', X1_Which_Version_Control_System_is_used__c='GIT',X2_Which_tool_is_used_for_Project_Manage__c='JIRA',Plz_specify_other_ALM__c='',How_often_Data_Loader__c='Daily',X1_Any_ETL_tool_currently_being_used__c ='Test',How_Often__c='monthly',How_are_metadata_components_being_dep__c='Ant Scripts',Plz_specify_other_Metadata_components__c='',Typically_how_many_records_do_you_mi__c ='50',What_are_the_pain_points_during_the_d__c='Test',How_long_does_it_take_for_pre_post_de__c='30'),
                new Questionnaire_Implementation__c(CreatedDate = DateTime.now(),  LastModifiedDate = DateTime.now(), Time_taken_for__c='30', Company_Name__c='Test', Email__c='test@test.com', What_kind_of_testing_do_you_perform__c='Apex only', What_does_your_current_release_process__c='Test', X1_Which_Version_Control_System_is_used__c='GIT',X2_Which_tool_is_used_for_Project_Manage__c='JIRA',Plz_specify_other_ALM__c='',How_often_Data_Loader__c='Daily',X1_Any_ETL_tool_currently_being_used__c ='Test',How_are_metadata_components_being_dep__c='Ant Scripts',Plz_specify_other_Metadata_components__c='',How_Often__c='monthly',Typically_how_many_records_do_you_mi__c ='50',What_are_the_pain_points_during_the_d__c='Test',How_long_does_it_take_for_pre_post_de__c='30'),
                new Questionnaire_Implementation__c(CreatedDate = DateTime.now(),  LastModifiedDate = DateTime.now(), Time_taken_for__c='30', Company_Name__c='Test', Email__c='test@test.com', What_kind_of_testing_do_you_perform__c='Apex only', What_does_your_current_release_process__c='Test', X1_Which_Version_Control_System_is_used__c='GIT',X2_Which_tool_is_used_for_Project_Manage__c='JIRA',Plz_specify_other_ALM__c='',How_often_Data_Loader__c='Daily',X1_Any_ETL_tool_currently_being_used__c ='Test',How_are_metadata_components_being_dep__c='Ant Scripts',Plz_specify_other_Metadata_components__c='',How_Often__c='monthly',Typically_how_many_records_do_you_mi__c ='50',What_are_the_pain_points_during_the_d__c='Test',How_long_does_it_take_for_pre_post_de__c='30'),
                new Questionnaire_Implementation__c(CreatedDate = DateTime.now(),  LastModifiedDate = DateTime.now(), Time_taken_for__c='30', Company_Name__c='Test', Email__c='test@test.com', What_kind_of_testing_do_you_perform__c='Apex only', What_does_your_current_release_process__c='Test', X1_Which_Version_Control_System_is_used__c='GIT',X2_Which_tool_is_used_for_Project_Manage__c='JIRA',Plz_specify_other_ALM__c='',How_often_Data_Loader__c='Daily',X1_Any_ETL_tool_currently_being_used__c ='Test',How_are_metadata_components_being_dep__c='Ant Scripts',Plz_specify_other_Metadata_components__c='',How_Often__c='monthly',Typically_how_many_records_do_you_mi__c ='50',What_are_the_pain_points_during_the_d__c='Test',How_long_does_it_take_for_pre_post_de__c='30')
                };
                    Insert questionnaire_implementation_Obj;
        test.stopTest();
    }
    static testMethod void test_getQuestionnaire_UseCase1(){
        List<Questionnaire_Implementation__c> questionnaire_implementation_Obj  =  [SELECT CreatedDate,CreatedById,LastModifiedDate,LastModifiedById from Questionnaire_Implementation__c];
        System.assertEquals(true,questionnaire_implementation_Obj.size()>0);
        
        
        Implementation_Questionnaire_1 obj01 = new Implementation_Questionnaire_1(new ApexPages.StandardController(questionnaire_implementation_Obj[0]));
        obj01.quesObj = questionnaire_implementation_Obj[0];
        obj01.isclick = false;
        obj01.questionPage = false;
        obj01.attach = new Attachment();
        obj01.attach1 = new Attachment();
        obj01.companyName = 'test data';
        obj01.Emailval = 'test data';
        Implementation_Questionnaire_1.DeveloperChanges = 'test data';
        Implementation_Questionnaire_1.codebackup = 'test data';
        Implementation_Questionnaire_1.timeDevelopers = 'test data';
        Implementation_Questionnaire_1.Nooftime = 'test data';
        Implementation_Questionnaire_1.Timetakenforcommits = 'test data';
        Implementation_Questionnaire_1.mergeconflictsaddressed = 'test data';
        obj01.leadList = new List<Lead>();
        obj01.selectedUseCases = 'test data';
        obj01.selectedUseCasesDeployment = 'test data';
        obj01.selectedUseCasesDataLoader = 'test data';
        obj01.usedOrNot = 'test data';
        obj01.getQuestionnaire();
    }
    static testMethod void test_getVersionControl_UseCase1(){
        List<Questionnaire_Implementation__c> questionnaire_implementation_Obj  =  [SELECT CreatedDate,CreatedById,LastModifiedDate,LastModifiedById from Questionnaire_Implementation__c];
        System.assertEquals(true,questionnaire_implementation_Obj.size()>0);
        
        Implementation_Questionnaire_1 obj01 = new Implementation_Questionnaire_1(new ApexPages.StandardController(questionnaire_implementation_Obj[0]));
        obj01.quesObj = questionnaire_implementation_Obj[0];
        obj01.isclick = false;
        obj01.questionPage = false;
        obj01.attach = new Attachment();
        obj01.attach1 = new Attachment();
        obj01.companyName = 'test data';
        obj01.Emailval = 'test data';
        Implementation_Questionnaire_1.DeveloperChanges = 'test data';
        Implementation_Questionnaire_1.codebackup = 'test data';
        Implementation_Questionnaire_1.timeDevelopers = 'test data';
        Implementation_Questionnaire_1.Nooftime = 'test data';
        Implementation_Questionnaire_1.Timetakenforcommits = 'test data';
        Implementation_Questionnaire_1.mergeconflictsaddressed = 'test data';
        obj01.leadList = new List<Lead>();
        obj01.selectedUseCases = 'test data';
        obj01.selectedUseCasesDeployment = 'test data';
        obj01.selectedUseCasesDataLoader = 'test data';
        obj01.usedOrNot = 'test data';
        obj01.getVersionControl();
    }
    static testMethod void test_getSelUseCases_UseCase1(){
        List<Questionnaire_Implementation__c> questionnaire_implementation_Obj  =  [SELECT CreatedDate,CreatedById,LastModifiedDate,LastModifiedById from Questionnaire_Implementation__c];
        System.assertEquals(true,questionnaire_implementation_Obj.size()>0);
        
        Implementation_Questionnaire_1 obj01 = new Implementation_Questionnaire_1(new ApexPages.StandardController(questionnaire_implementation_Obj[0]));
        obj01.quesObj = questionnaire_implementation_Obj[0];
        obj01.isclick = false;
        obj01.questionPage = false;
        obj01.attach = new Attachment();
        obj01.attach1 = new Attachment();
        obj01.companyName = 'test data';
        obj01.Emailval = 'test data';
        Implementation_Questionnaire_1.DeveloperChanges = 'test data';
        Implementation_Questionnaire_1.codebackup = 'test data';
        Implementation_Questionnaire_1.timeDevelopers = 'test data';
        Implementation_Questionnaire_1.Nooftime = 'test data';
        Implementation_Questionnaire_1.Timetakenforcommits = 'test data';
        Implementation_Questionnaire_1.mergeconflictsaddressed = 'test data';
        obj01.leadList = new List<Lead>();
        obj01.selectedUseCases = 'test data';
        obj01.selectedUseCasesDeployment = 'test data';
        obj01.selectedUseCasesDataLoader = 'test data';
        obj01.usedOrNot = 'test data';
        obj01.getSelUseCases();
    }
    static testMethod void test_getSelUseCasesDeployment_UseCase1(){
        List<Questionnaire_Implementation__c> questionnaire_implementation_Obj  =  [SELECT CreatedDate,CreatedById,LastModifiedDate,LastModifiedById from Questionnaire_Implementation__c];
        System.assertEquals(true,questionnaire_implementation_Obj.size()>0);
        
        Implementation_Questionnaire_1 obj01 = new Implementation_Questionnaire_1(new ApexPages.StandardController(questionnaire_implementation_Obj[0]));
        obj01.quesObj = questionnaire_implementation_Obj[0];
        obj01.isclick = false;
        obj01.questionPage = false;
        obj01.attach = new Attachment();
        obj01.attach1 = new Attachment();
        obj01.companyName = 'test data';
        obj01.Emailval = 'test data';
        Implementation_Questionnaire_1.DeveloperChanges = 'test data';
        Implementation_Questionnaire_1.codebackup = 'test data';
        Implementation_Questionnaire_1.timeDevelopers = 'test data';
        Implementation_Questionnaire_1.Nooftime = 'test data';
        Implementation_Questionnaire_1.Timetakenforcommits = 'test data';
        Implementation_Questionnaire_1.mergeconflictsaddressed = 'test data';
        obj01.leadList = new List<Lead>();
        obj01.selectedUseCases = 'test data';
        obj01.selectedUseCasesDeployment = 'test data';
        obj01.selectedUseCasesDataLoader = 'test data';
        obj01.usedOrNot = 'test data';
        obj01.getSelUseCasesDeployment();
    }
    static testMethod void test_getSelUseCasesDataLoader_UseCase1(){
        List<Questionnaire_Implementation__c> questionnaire_implementation_Obj  =  [SELECT CreatedDate,CreatedById,LastModifiedDate,LastModifiedById from Questionnaire_Implementation__c];
        System.assertEquals(true,questionnaire_implementation_Obj.size()>0);
        
        Implementation_Questionnaire_1 obj01 = new Implementation_Questionnaire_1(new ApexPages.StandardController(questionnaire_implementation_Obj[0]));
        obj01.quesObj = questionnaire_implementation_Obj[0];
        obj01.isclick = false;
        obj01.questionPage = false;
        obj01.attach = new Attachment();
        obj01.attach1 = new Attachment();
        obj01.companyName = 'test data';
        obj01.Emailval = 'test data';
        Implementation_Questionnaire_1.DeveloperChanges = 'test data';
        Implementation_Questionnaire_1.codebackup = 'test data';
        Implementation_Questionnaire_1.timeDevelopers = 'test data';
        Implementation_Questionnaire_1.Nooftime = 'test data';
        Implementation_Questionnaire_1.Timetakenforcommits = 'test data';
        Implementation_Questionnaire_1.mergeconflictsaddressed = 'test data';
        obj01.leadList = new List<Lead>();
        obj01.selectedUseCases = 'test data';
        obj01.selectedUseCasesDeployment = 'test data';
        obj01.selectedUseCasesDataLoader = 'test data';
        obj01.usedOrNot = 'test data';
        obj01.getSelUseCasesDataLoader();
    }
    static testMethod void test_searchdata_UseCase1(){
        List<Questionnaire_Implementation__c> questionnaire_implementation_Obj  =  [SELECT CreatedDate,CreatedById,LastModifiedDate,LastModifiedById from Questionnaire_Implementation__c];
        System.assertEquals(true,questionnaire_implementation_Obj.size()>0);
        
        Implementation_Questionnaire_1 obj01 = new Implementation_Questionnaire_1(new ApexPages.StandardController(questionnaire_implementation_Obj[0]));
        obj01.quesObj = questionnaire_implementation_Obj[0];
        obj01.isclick = false;
        obj01.questionPage = false;
        obj01.attach = new Attachment();
        obj01.attach1 = new Attachment();
        obj01.companyName = 'test data';
        obj01.Emailval = 'test data';
        Implementation_Questionnaire_1.DeveloperChanges = 'test data';
        Implementation_Questionnaire_1.codebackup = 'test data';
        Implementation_Questionnaire_1.timeDevelopers = 'test data';
        Implementation_Questionnaire_1.Nooftime = 'test data';
        Implementation_Questionnaire_1.Timetakenforcommits = 'test data';
        Implementation_Questionnaire_1.mergeconflictsaddressed = 'test data';
        obj01.leadList = new List<Lead>();
        obj01.selectedUseCases = 'test data';
        obj01.selectedUseCasesDeployment = 'test data';
        obj01.selectedUseCasesDataLoader = 'test data';
        obj01.usedOrNot = 'test data';
        obj01.searchdata();
    }
    static testMethod void test_Save_UseCase1(){
        Questionnaire_Implementation__c ques=new Questionnaire_Implementation__c();
        List<Questionnaire_Implementation__c> questionnaire_implementation_Obj = [SELECT CreatedDate,CreatedById,LastModifiedDate,LastModifiedById,X1_Which_Version_Control_System_is_used__c, Name_of_other_System__c, X2_Which_tool_is_used_for_Project_Manage__c,
                                                                                  Plz_specify_other_ALM__c, No_of_time__c,What_is_the_current_team_structure_w__c, Plz_specify_others__c,Developer_Changes_how_do_you_track__c,How_are_metadata_components_being_dep__c,Plz_specify_other_Metadata_components__c  from Questionnaire_Implementation__c];
        System.assertEquals(true,questionnaire_implementation_Obj.size()>0); 
        //   	 System.assertEquals(false, ApexPages.hasMessages(), 'Expected that there would be a page message after running the test');
        Implementation_Questionnaire_1 obj01 = new Implementation_Questionnaire_1(new ApexPages.StandardController(questionnaire_implementation_Obj[0]));
        PageReference pageRef = Page.ThankYouPage; // Add your VF page Name here
        Test.setCurrentPage(pageRef);
        obj01.quesObj = questionnaire_implementation_Obj[0];
        obj01.isclick = false;
        obj01.questionPage = false;
        obj01.attach = new Attachment();
        obj01.attach1 = new Attachment();
        obj01.companyName = 'test data';
        obj01.Emailval = 'test data';
        Implementation_Questionnaire_1.DeveloperChanges = 'test data';
        Implementation_Questionnaire_1.codebackup = 'test data';
        Implementation_Questionnaire_1.timeDevelopers = 'test data';
        Implementation_Questionnaire_1.Nooftime = 'test data';
        Implementation_Questionnaire_1.Timetakenforcommits = 'test data';
        Implementation_Questionnaire_1.mergeconflictsaddressed = 'test data';
        obj01.leadList = new List<Lead>();
        obj01.selectedUseCases = 'test data';
        obj01.selectedUseCasesDeployment = 'test data';
        obj01.selectedUseCasesDataLoader = 'test data';
        obj01.usedOrNot = 'test data';
        obj01.Save();
        system.assert(obj01.quesObj.Id != null);
        
        Test.StartTest(); 
        
        apexPages.Currentpage().getParameters().put('Id',obj01.quesObj.id);
        Implementation_Questionnaire_1 testAccPlan = new Implementation_Questionnaire_1();
        testAccPlan.shootLasers(5);
        testAccPlan.khootLasers(5);
        testAccPlan.BootLasers(5);
        testAccPlan.ChootLasers(5);
        //testAccPlan.save(); call all your function here
        Test.StopTest();
    }
    
}