objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Discount_Given__c</fullName>
        <label>Discount Given %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <description>Quantity*Sale Price*number of months</description>
        <formula>if( Is_this_PS__c = false, ( of_Months__c * Quantity *  UnitPrice ), Quantity *  UnitPrice)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Quantity*Sale Price*number of months</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_List_Price__c</fullName>
        <formula>Quantity* PricebookEntry.UnitPrice</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total List Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>of_Months__c</fullName>
        <defaultValue>12</defaultValue>
        <label># of Months</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/QuoteLineItemCtrl.cls
public class QuoteLineItemCtrl {
    public id qId{get;set;}
    public list<QuoteLineItem> quoteItemList{get;set;}
    public QuoteLineItemCtrl(){}
    public list<QuoteLineItem> getQuoteItemsList(){
       quoteItemList= new list<QuoteLineItem>();
       quoteItemList=[SELECT Id, Product2.Name,Product2.CreatedDate, 
                       ListPrice, UnitPrice,Total_Amount__c,of_Months__c,
                       Quantity, Discount_Given__c, 
                       Total_List_Price__c, QuoteId,createddate 
                       FROM QuoteLineItem 
                       where QuoteId=:qId];
       system.debug('---------------------------------------------------------------------'+[SELECT Id, Product2.Name, 
                       ListPrice, UnitPrice, 
                       Quantity, Discount_Given__c, of_Months__c,
                       Total_List_Price__c, QuoteId 
                       FROM QuoteLineItem 
                       where QuoteId=:qId]);                
       return quoteItemList;                
    }
}