objects/SDR_Metrics__c.object
<CustomObject>
    <fields>
        <fullName>DC_Completed_Date_Vault__c</fullName>
        <label>DC Completed Date Vault</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DC_Completed_Date__c</fullName>
        <label>DC Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DC_Scheduled_Date_Vault__c</fullName>
        <label>DC Scheduled Date (Vault)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DC_Scheduled_Date__c</fullName>
        <label>DC Scheduled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Demo_Performed_Date_Vault__c</fullName>
        <label>Demo Performed Date (Vault)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Demo_Performed_Date__c</fullName>
        <label>Demo Performed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Demo_Scheduled_Date__c</fullName>
        <label>Demo Scheduled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SDR__c</fullName>
        <formula>if(isBlank(Contact__c),if(isBlank(Lead_1__c),Null, Lead_1__r.SDR__c ),IF ( INCLUDES ( Contact__r.SDR__c  , &quot;Arvind&quot; ), &quot;Arvind Tripathy&quot;,IF ( INCLUDES ( Contact__r.SDR__c  , &quot;Nick Garcia&quot; ), &quot;Nick Garcia&quot;,IF ( INCLUDES ( Contact__r.SDR__c  , &quot;Sherdah Moca&quot; ), &quot;Sherdah Moca&quot;,IF ( INCLUDES ( Contact__r.SDR__c  , &quot;Shiva Kumar Gatla&quot; ), &quot;Shiva Kumar Gatla&quot;,IF ( INCLUDES ( Contact__r.SDR__c  , &quot;Venkatesh T&quot; ), &quot;Venkatesh Thadanola&quot;,IF ( INCLUDES ( Contact__r.SDR__c  , &quot;Christina Blanco&quot; ), &quot;Christina Blanco&quot;,IF ( INCLUDES ( Contact__r.SDR__c  , &quot;Krishna Chaitanya&quot; ), &quot;Krishna Chaitanya&quot;,IF ( INCLUDES ( Contact__r.SDR__c  , &quot;KC&quot; ),&quot;Krishna Chaitanya&quot;,IF ( INCLUDES ( Contact__r.SDR__c  , &quot;Belinda&quot; ),&quot;Belinda&quot;,IF ( INCLUDES ( Contact__r.SDR__c  , &quot;Kainaz&quot; ),&quot;Kainaz&quot;,IF ( INCLUDES ( Contact__r.SDR__c  , &quot;Amrit&quot; ),&quot;Amrita&quot;,IF ( INCLUDES ( Contact__r.SDR__c  , &quot;Matt&quot; ),&quot;Matt&quot;,IF ( INCLUDES ( Contact__r.SDR__c  , &quot;Mukesh&quot; ),&quot;Mukesh&quot;,NULL))))))))))))))</formula>
        <label>SDR</label>
        <type>Text</type>
    </fields>
    <label>SDR Metric</label>
    <nameField>
        <label>SDR Metrics Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SDR Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchCls_DeleteSDR_Metrics_Test.cls
@isTest
public class BatchCls_DeleteSDR_Metrics_Test {
    @isTest
    public static void TestDeletionSDR_Metrics(){
        Account accInfo = new Account(Name= 'acc1');
        Insert accInfo;
        
        Contact cntctInfo = new Contact(AccountId  = accInfo.id,LastName = 'XYZ',Phone = '123456790',Email ='xyz@autorabbit.com',DC_Completed_Date__c = date.today(),DC_Completed_Date_Vault__c = date.today() + 2,DC_Scheduled_Date__c = DATE.today() + 4,
                                       DC_Scheduled_Date_Vault__c = Date.today() + 6,Demo_Performed_Date__c = date.today() -3,Demo_Performed_Date_Vault__c = date.today() - 2,Demo_Scheduled_Date__c = date.today() + 3);
        
        insert cntctInfo;
        
        Lead leadInfo = new Lead(SDR__c = 'sdr1',Company = 'autorabbit',Status = 'Qualified',Email = 'xyz@autorabbit.com',LastName = 'xyz',	Partner_Enterprise__c = 'Enterprise',DC_Completed_Date__c = date.today() + 4,
                               DC_Completed_Date_Vault__c = date.today() - 3,DC_Scheduled_On__c = date.today() + 7,DC_Scheduled_On_Vault__c = date.today() + 2,Demo_Performed_Date__c = date.today() + 6,Demo_Performed_Date_VaultI0__c = date.today() -3,Demo_Scheduled_Date__c = date.today() + 2);
        
        Insert leadInfo;
        
        List<SDR_Metrics__c> sdrList = new List<SDR_Metrics__c>();
		for(Integer i = 0 ;i<100;i++){
    		SDR_Metrics__c sdrinfo  = new SDR_Metrics__c();
    		sdrinfo.name = 'sdr'+i;
    		sdrList.add(sdrInfo);
		}
		insert sdrList;
        
        Test.startTest();
        String query = 'Select id from SDR_Metrics__c limit 50000';
        BatchCls_DeleteSDR_Metrics  btchDeletesdRMetrics= new BatchCls_DeleteSDR_Metrics(query);
        database.executeBatch(btchDeletesdRMetrics);
        Test.stopTest();
        
    } 
}