objects/SDR_Metrics__c.object
<CustomObject>
    <fields>
        <fullName>DC_Completed_Date_Vault__c</fullName>
        <label>DC Completed Date Vault</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DC_Completed_Date__c</fullName>
        <label>DC Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DC_Demo__c</fullName>
        <label>DC &amp; Demo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>DC Completed</fullName>
                </value>
                <value>
                    <fullName>DC Completed Date (Vault)</fullName>
                </value>
                <value>
                    <fullName>DC Scheduled</fullName>
                </value>
                <value>
                    <fullName>DC Scheduled (Vault)</fullName>
                </value>
                <value>
                    <fullName>DC Scheduled For</fullName>
                </value>
                <value>
                    <fullName>DC Scheduled For (Vault)</fullName>
                </value>
                <value>
                    <fullName>Demo Performed</fullName>
                </value>
                <value>
                    <fullName>Demo_Performed(Vault)</fullName>
                    <label>Demo Performed(Vault)</label>
                </value>
                <value>
                    <fullName>Demo Scheduled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Demo_Performed_Date__c</fullName>
        <label>Demo Performed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Demo_Scheduled_Date__c</fullName>
        <label>Demo Scheduled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lead_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead 1</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>SDR Metrics</relationshipLabel>
        <relationshipName>SDR_Metrics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SDR_Name__c</fullName>
        <label>SDR_Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SDR__c</fullName>
        <formula>if(isBlank(Contact__c),if(isBlank(Lead_1__c),Null, Lead_1__r.SDR__c ),IF ( INCLUDES ( Contact__r.SDR__c  , &quot;Arvind&quot; ), &quot;Arvind Tripathy&quot;,IF ( INCLUDES ( Contact__r.SDR__c  , &quot;Nick Garcia&quot; ), &quot;Nick Garcia&quot;,IF ( INCLUDES ( Contact__r.SDR__c  , &quot;Sherdah Moca&quot; ), &quot;Sherdah Moca&quot;,IF ( INCLUDES ( Contact__r.SDR__c  , &quot;Shiva Kumar Gatla&quot; ), &quot;Shiva Kumar Gatla&quot;,IF ( INCLUDES ( Contact__r.SDR__c  , &quot;Venkatesh T&quot; ), &quot;Venkatesh Thadanola&quot;,IF ( INCLUDES ( Contact__r.SDR__c  , &quot;Christina Blanco&quot; ), &quot;Christina Blanco&quot;,IF ( INCLUDES ( Contact__r.SDR__c  , &quot;Krishna Chaitanya&quot; ), &quot;Krishna Chaitanya&quot;,IF ( INCLUDES ( Contact__r.SDR__c  , &quot;KC&quot; ),&quot;Krishna Chaitanya&quot;,IF ( INCLUDES ( Contact__r.SDR__c  , &quot;Belinda&quot; ),&quot;Belinda&quot;,IF ( INCLUDES ( Contact__r.SDR__c  , &quot;Kainaz&quot; ),&quot;Kainaz&quot;,IF ( INCLUDES ( Contact__r.SDR__c  , &quot;Amrit&quot; ),&quot;Amrita&quot;,IF ( INCLUDES ( Contact__r.SDR__c  , &quot;Matt&quot; ),&quot;Matt&quot;,IF ( INCLUDES ( Contact__r.SDR__c  , &quot;Mukesh&quot; ),&quot;Mukesh&quot;,NULL))))))))))))))</formula>
        <label>SDR</label>
        <type>Text</type>
    </fields>
    <label>SDR Metric</label>
    <nameField>
        <label>SDR Metrics Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SDR Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CLS_InsertSdrData.cls
global class CLS_InsertSdrData implements Database.Batchable<Sobject> {
    
    global  database.queryLocator start(Database.BatchableContext Bc){
        return database.getQueryLocator('Select id, name,SDR__c, DC_Completed_Date__c, DC_Completed_Date_Vault__c, DC_Scheduled_On__c, DC_Scheduled_On_Vault__c, Demo_Performed_Date__c,Demo_Performed_Date_VaultI0__c, Demo_Scheduled_Date__c from Lead where DC_Completed_Date__c != Null OR DC_Completed_Date_Vault__c!= Null OR DC_Scheduled_On__c!= Null OR DC_Scheduled_On_Vault__c != Null OR Demo_Performed_Date__c != Null OR Demo_Performed_Date_VaultI0__c != Null OR Demo_Scheduled_Date__c != Null');
    }
    
    global static void Execute(Database.BatchableContext bc,List<Lead> listOfLeadsToBeInsertedAsSdr){
        list<SDR_Metrics__c> sdrList = new list<SDR_Metrics__c>();

		for(Lead l : listOfLeadsToBeInsertedAsSdr)
        {

    		if(l.DC_Completed_Date__c != Null)

    		{

        		SDR_Metrics__c sdrRecord = new SDR_Metrics__c();

        		sdrRecord.Lead_1__c = l.Id;

                sdrRecord.Date__c = l.DC_Completed_Date__c;

        		sdrRecord.DC_Demo__c = 'DC Completed';

        		sdrRecord.SDR_Name__c = l.SDR__c;

        		sdrList.add(sdrRecord);

    		}

   

    		if(l.DC_Completed_Date_Vault__c != Null)

    		{

                SDR_Metrics__c sdrRecord = new SDR_Metrics__c();
        
                sdrRecord.Lead_1__c = l.Id;
        
                sdrRecord.Date__c = l.DC_Completed_Date_Vault__c;
        
                sdrRecord.DC_Demo__c = 'DC Completed Date (Vault)';
        
                sdrRecord.SDR_Name__c = l.SDR__c;
        
                sdrList.add(sdrRecord);

    		}

   

    		if(l.DC_Scheduled_On__c != Null)

    		{

                SDR_Metrics__c sdrRecord = new SDR_Metrics__c();
        
                sdrRecord.Lead_1__c = l.Id;
        
                sdrRecord.Date__c = l.DC_Scheduled_On__c;
        
                sdrRecord.DC_Demo__c = 'DC Scheduled';
        
                sdrRecord.SDR_Name__c = l.SDR__c;
        
                sdrList.add(sdrRecord);

    		}

   

    		if(l.DC_Scheduled_On_Vault__c != Null)

    		{

                SDR_Metrics__c sdrRecord = new SDR_Metrics__c();
        
                sdrRecord.Lead_1__c = l.Id;
        
                sdrRecord.Date__c = l.DC_Scheduled_On_Vault__c;
        
                sdrRecord.DC_Demo__c = 'DC Scheduled (Vault)';
        
                sdrRecord.SDR_Name__c = l.SDR__c;
        
                sdrList.add(sdrRecord);

    		}

   

    		if(l.Demo_Performed_Date__c != Null)

    		{

                SDR_Metrics__c sdrRecord = new SDR_Metrics__c();
        
                sdrRecord.Lead_1__c = l.Id;
        
                sdrRecord.Date__c = l.Demo_Performed_Date__c;
        
                sdrRecord.DC_Demo__c = 'Demo Performed';
        
                sdrRecord.SDR_Name__c = l.SDR__c;
        
                sdrList.add(sdrRecord);

    		}

   

    		if(l.Demo_Performed_Date_VaultI0__c != Null)

    		{

                SDR_Metrics__c sdrRecord = new SDR_Metrics__c();
        
                sdrRecord.Lead_1__c = l.Id;
        
                sdrRecord.Date__c = l.Demo_Performed_Date_VaultI0__c;
        
                sdrRecord.DC_Demo__c = 'Demo_Performed(Vault)';
        
                sdrRecord.SDR_Name__c = l.SDR__c;
        
                sdrList.add(sdrRecord);

    		}

   

    		if(l.Demo_Scheduled_Date__c != Null)

    		{

                SDR_Metrics__c sdrRecord = new SDR_Metrics__c();
        
                sdrRecord.Lead_1__c = l.Id;
        
                sdrRecord.Date__c = l.Demo_Scheduled_Date__c;
        
                sdrRecord.DC_Demo__c = 'Demo Scheduled';
        
                sdrRecord.SDR_Name__c = l.SDR__c;
        
                sdrList.add(sdrRecord);

    		}

   

 	}
        if(SdrList.size()>0){
		insert sdrList;
        }
        
    }
    
    global void finish(Database.BatchableContext Bc){
        
        Database.executeBatch(new BatchCls_InsertSDRFromContact());
    }
    
}