objects/SFDC_Volunteer_Event__c.object
<CustomObject>
    <description>Used to manage and track vounteer events</description>
    <fields>
        <fullName>Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Meeting Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Facilitator_Being_Recruited__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check box for OE coordinator to indicate that the meeting should go into the pool for ambassador recruitment</description>
        <label>Facilitator Being Recruited</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Facilitator_Feedback_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <description>(LG201427) Please check with dev team before modifing- this field is updated with a force.com site  Facilitator Feedback has been entered into the system</description>
        <label>Facilitator Feedback Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Facilitator_Secured__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used by Open Enrollment to indicate that the facilitator(s) has been secured for the meeting.  This should trigger an email to be sent out to the facilitator</description>
        <label>Facilitator Secured</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Feedback_Not_Received_Within_14_Days__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Feedback Not Received Within 14 Days</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Materials_Delivered__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to indicate a confirmation of shippment email was received.</description>
        <label>Materials Delivered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Materials_Needed__c</fullName>
        <label>Materials Needed</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Promo only needed</fullName>
                </value>
                <value>
                    <fullName>Collateral only needed</fullName>
                </value>
                <value>
                    <fullName>Promo and Collateral Needed</fullName>
                </value>
                <value>
                    <fullName>No Promo or Collateral Needed</fullName>
                </value>
                <value>
                    <fullName>OE Kit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Materials_Order_On_Standby__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Materials order is too early to place.</description>
        <label>Materials Order On Standby</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Materials_Order_placed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Materials Order has been placed</description>
        <label>Materials Order placed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Meeting_Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Meeting Cancelled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Meeting_Stage__c</fullName>
        <description>This field shows where the meeting is in the entry process.</description>
        <inlineHelpText>Change status to SUBMITTED when all fields have been entered and the meeting is ready for validation and submission to the OE Coordinator.</inlineHelpText>
        <label>Meeting Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DRAFT</fullName>
                    <default>true</default>
                    <label>DRAFT</label>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>SUBMITTED</fullName>
                </value>
                <value>
                    <fullName>Submitted - Rush</fullName>
                </value>
                <value>
                    <fullName>UPDATED</fullName>
                </value>
                <value>
                    <fullName>Updated - Rush</fullName>
                </value>
                <value>
                    <fullName>COMPLETE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Meeting_Status__c</fullName>
        <inlineHelpText>(LG06232014)Field is updated by workflows please do not change.</inlineHelpText>
        <label>Meeting Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>COMPLETED-CANCELLED</fullName>
                </value>
                <value>
                    <fullName>NEW REQUEST</fullName>
                    <default>true</default>
                    <label>NEW REQUEST</label>
                </value>
                <value>
                    <fullName>IN REVIEW</fullName>
                </value>
                <value>
                    <fullName>IN PROCESS – FACILITATOR BEING RECRUITED</fullName>
                </value>
                <value>
                    <fullName>IN PROCESS - FACILITATOR SECURED AND WAITING ON FEEDBACK</fullName>
                </value>
                <value>
                    <fullName>COMPLETED - FACILITATOR SECURED &amp;MEETING FEEDBACK RECEIVED</fullName>
                </value>
                <value>
                    <fullName>COMPLETED - MATERIALS DELIVERED</fullName>
                </value>
                <value>
                    <fullName>IN PROCESS – ORDER ON STANDBY</fullName>
                </value>
                <value>
                    <fullName>IN PROCESS- ORDER PLACED</fullName>
                </value>
                <value>
                    <fullName>IN PROCESS – FACILITATOR BEING RECRUITED &amp; ORDER on STANDBY</fullName>
                </value>
                <value>
                    <fullName>IN PROCESS -FACILITATOR SECURED  &amp; WAITING ON FEEDBACK &amp; ORDER ON STANDBY</fullName>
                </value>
                <value>
                    <fullName>IN PROCESS- FACILITATOR SECURED &amp; WAITING ON FEEDBACK &amp; ORDER PLACED</fullName>
                </value>
                <value>
                    <fullName>IN PROCESS -FACILITATOR BEING RECRUITED &amp; ORDER PLACED</fullName>
                </value>
                <value>
                    <fullName>IN PROCESS- FACILITATOR SECURED &amp; MATERIALS DELIVERED &amp; WAITING ON FEEDBACK</fullName>
                </value>
                <value>
                    <fullName>COMPLETED - FACILITATOR SECURED &amp; MATERIALS DELIVERED &amp; MEETING FEEDBACK RECEIVED</fullName>
                </value>
                <value>
                    <fullName>COMPLETED - UNABLE TO SECURE FACILITATOR &amp; MATERIALS DELIVERED</fullName>
                </value>
                <value>
                    <fullName>COMPLETED - UNABLE TO SECURE FACILITATOR</fullName>
                </value>
                <value>
                    <fullName>COMPLETED- FACILITATOR SECURED AND FEEDBACK NOT RECEIVED WITHIN 14 DAYS</fullName>
                </value>
                <value>
                    <fullName>Completed Cancelled - Override</fullName>
                </value>
                <value>
                    <fullName>OE KIT REQUEST ONLY</fullName>
                </value>
                <value>
                    <fullName>IN PROCESS -UNABLE TO SECURE FACILITATOR - ORDER PLACED</fullName>
                </value>
                <value>
                    <fullName>IN PROCESS - UNABLE TO SECURE FACILITATOR - ORDER ON STANDBY</fullName>
                </value>
                <value>
                    <fullName>COMPLETED- FACILITATOR SECURED &amp; MATERIALS DELIVERED &amp; FEEDBACK NOT RECEIVED WITHIN 14 DAYS</fullName>
                </value>
                <value>
                    <fullName>IN PROCESS - FACILITATOR SECURED &amp;  ORDER PLACED &amp; WAITING ON FEEDBACK</fullName>
                </value>
                <value>
                    <fullName>IN PROCESS -FACILITATOR BEING RECRUITED &amp; MATERIALS DELIVERED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RUSH__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Changes done under user story: PRDCRM - 27697</description>
        <inlineHelpText>Meeting Date less than or equal to 14 days from today</inlineHelpText>
        <label>RUSH</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reason_for_Update__c</fullName>
        <inlineHelpText>Select a reason for the change to assist the OE Coordinator.</inlineHelpText>
        <label>Reason for Update</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Meeting cancelled</fullName>
                </value>
                <value>
                    <fullName>Date Change</fullName>
                </value>
                <value>
                    <fullName>Session times change</fullName>
                </value>
                <value>
                    <fullName>Meeting address change</fullName>
                </value>
                <value>
                    <fullName>Delivery address change</fullName>
                </value>
                <value>
                    <fullName>Site contact name/ph# change</fullName>
                </value>
                <value>
                    <fullName>Facilitator Update</fullName>
                </value>
                <value>
                    <fullName>Materials Change</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>OE Kit Approved</fullName>
                </value>
                <value>
                    <fullName>OE Kit Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recruitment_of_Facilitator_Needed__c</fullName>
        <description>AM checks this if they will not be attending or if they don&apos;t already have a facilitator lined up.</description>
        <inlineHelpText>If Yes Open Enrollment Team will seek coverage.</inlineHelpText>
        <label>Facilitator Needs to be Recruited</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>User checks box when meeting is ready for processing by OE</description>
        <inlineHelpText>Check this box when the meeting is ready for processing.</inlineHelpText>
        <label>Submit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unable_to_secure_facilitator__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This box is checked when recruitment of a facilitator was unsuccessful</description>
        <label>Unable to secure facilitator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Waiting_on_Feedback__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Facilitator Feedback has not been received</description>
        <label>Waiting on Facilitator Feedback</label>
        <type>Checkbox</type>
    </fields>
    <label>Open Enrollment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Enrollment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OpenEnrollmentTriggerAction.cls
/*************************************************************************************
    Version           : 1.0 
    @Author          : Mehaboob
    @description    :Open Enrollment Hnadler for updating stage status values
    @comment     : Created this class as part of Story PRDCRM-45610 and 43212
    OpenEnrollmentStageStatusTest is the test class for this Apex class 
    Created on : 10/30/2010               
    **************************************************************************************
    @mod : 11/11/2019
    @comment : modified class name to 'OpenEnrollmentTriggerAction'   as part of story PRDCRM-43213
    
    **************************************************************************************
    @mod : 1/20/2020
    @comment : modified this  class as per the updated sheet .related to PRDCRM- 50758
    
    *************************************************************************************/
    public with Sharing class OpenEnrollmentTriggerAction{
        
        
        /*
    @description : Method to update OE Stage Status 
    */
        public static void updateStageStatus(List<SFDC_Volunteer_Event__c> newOpenEnrollmentList, Map<Id, SFDC_Volunteer_Event__c> oldOpenEnrollmentMap,Boolean isInsert){
           
            
            for(SFDC_Volunteer_Event__c openEnrlment: newOpenEnrollmentList){
                
              System.debug('inside for loop ---'+openEnrlment.Recruitment_of_Facilitator_Needed__c);
                SFDC_Volunteer_Event__c oldOE =new SFDC_Volunteer_Event__c();
                //Checking for only updates 
                if(!isInsert){
                    if(oldOpenEnrollmentMap.size()>0 && oldOpenEnrollmentMap.containsKey(openEnrlment.ID)){ 
                        oldOE = oldOpenEnrollmentMap.get(openEnrlment.ID);
                    }
                }
                System.debug('OLDOE'+oldOE);
                
                
                //Updating Rush to true based on the meeting date 
                if((openEnrlment.Date__c!=null) && openEnrlment.Date__c<= System.TODAY()+13 && openEnrlment.Meeting_Stage__c=='SUBMITTED' && openEnrlment.Meeting_Stage__c!='DRAFT'){
                        openEnrlment.RUSH__c=true;
                }
                
                if(openEnrlment!=oldOE)
                {
                 //Stage status value updation goes below with various criteria 
                 if(openEnrlment.Date__c<=System.TODAY() + 13 && openEnrlment.Meeting_Stage__c=='SUBMITTED'){
                        
                        openEnrlment.Meeting_Stage__c=UtilConstants.STATUS_SUB_RUSH ;
                        openEnrlment.Meeting_Status__c=UtilConstants.STATUS_NEW_REQUEST; 
                        openEnrlment.RUSH__c =true;
                
                }
                
                
                else if(openEnrlment.Meeting_Cancelled__c==true && openEnrlment.Submit__c==true){
                        
                        openEnrlment.Meeting_Stage__c=UtilConstants.STAGE_COMPLETE;
                        openEnrlment.Meeting_Status__c=UtilConstants.STATUS_COMPLETED_CANCELLED;
                
                }
                else if((openEnrlment.Reason_for_Update__c!='' && openEnrlment.Reason_for_Update__c!=null) && openEnrlment.Reason_for_Update__c!=oldOE.Reason_for_Update__c && openEnrlment.Submit__c==true && openEnrlment.Date__c<= System.TODAY() + 13){
                        
                        openEnrlment.Meeting_Stage__c=UtilConstants.STAGE_UPDATED_RUSH;
                        
                }
                
                else if((openEnrlment.Reason_for_Update__c!='' && openEnrlment.Reason_for_Update__c!=null) && openEnrlment.Reason_for_Update__c!=oldOE.Reason_for_Update__c && openEnrlment.Submit__c==true && openEnrlment.Date__c>= System.TODAY() +13){
                        
                        openEnrlment.Meeting_Stage__c=UtilConstants.STAGE_UPDATED;
                    
                
                }
                
                else if(openEnrlment.Recruitment_of_Facilitator_Needed__c==UtilConstants.REC_OF_FACILITATOR_NEEDED_YES && openEnrlment.Materials_Needed__c==UtilConstants.NO_PROMO_OR_COLLATERAL_NEEDED  && openEnrlment.Facilitator_Being_Recruited__c==false 
                        && openEnrlment.Facilitator_Secured__c==true && openEnrlment.Unable_to_secure_facilitator__c==false && openEnrlment.Waiting_on_Feedback__c==false&& openEnrlment.Feedback_Not_Received_Within_14_Days__c==false 
                        && openEnrlment.Facilitator_Feedback_Received__c==true && openEnrlment.Materials_Order_On_Standby__c==false && openEnrlment.Materials_Order_placed__c==false && openEnrlment.Materials_Delivered__c==false 
                        && openEnrlment.Meeting_Cancelled__c==false && openEnrlment.Submit__c==true ){
                          
                          System.debug('Entered If'+openEnrlment.Recruitment_of_Facilitator_Needed__c);  
                            openEnrlment.Meeting_Stage__c=UtilConstants.STAGE_COMPLETE;
                            openEnrlment.Meeting_Status__c=UtilConstants.STATUS_COMPLETED_FAC_SEC_AND_MEETING_FEED_REC;
                
                }else if(openEnrlment.Recruitment_of_Facilitator_Needed__c==UtilConstants.REC_OF_FACILITATOR_NEEDED_YES && openEnrlment.Materials_Needed__c==UtilConstants.NO_PROMO_OR_COLLATERAL_NEEDED  && openEnrlment.Facilitator_Being_Recruited__c==false 
                        && openEnrlment.Facilitator_Secured__c==true && openEnrlment.Unable_to_secure_facilitator__c==false && openEnrlment.Waiting_on_Feedback__c==false && openEnrlment.Feedback_Not_Received_Within_14_Days__c==true 
                        && openEnrlment.Facilitator_Feedback_Received__c==false && openEnrlment.Materials_Order_On_Standby__c==false && openEnrlment.Materials_Order_placed__c==false && openEnrlment.Materials_Delivered__c==false 
                        && openEnrlment.Meeting_Cancelled__c==false && openEnrlment.Submit__c==true ){
                        
                            openEnrlment.Meeting_Stage__c=UtilConstants.STAGE_COMPLETE;
                            openEnrlment.Meeting_Status__c=UtilConstants.STATUS_COMPLETED_FAC_SEC_AND_FEED_NOT_REC_WITHIN_14_DAYS;
                
                }else if(openEnrlment.Recruitment_of_Facilitator_Needed__c==UtilConstants.REC_OF_FACILITATOR_NEEDED_YES && openEnrlment.Materials_Needed__c==UtilConstants.NO_PROMO_OR_COLLATERAL_NEEDED  && openEnrlment.Facilitator_Being_Recruited__c==false 
                        && openEnrlment.Facilitator_Secured__c==true && openEnrlment.Unable_to_secure_facilitator__c==false && openEnrlment.Waiting_on_Feedback__c==true && openEnrlment.Feedback_Not_Received_Within_14_Days__c==false 
                        && openEnrlment.Facilitator_Feedback_Received__c==false && openEnrlment.Materials_Order_On_Standby__c==false && openEnrlment.Materials_Order_placed__c==false && openEnrlment.Materials_Delivered__c==false 
                        && openEnrlment.Meeting_Cancelled__c==false && openEnrlment.Submit__c==true ){
                        
                            openEnrlment.Meeting_Stage__c=UtilConstants.STAGE_INPROCESS;
                            openEnrlment.Meeting_Status__c=UtilConstants.STATUS_INPROCESS_FAC_SEC_AND_WAITING_ON_FEED;
                
                }else if(openEnrlment.Recruitment_of_Facilitator_Needed__c==UtilConstants.REC_OF_FACILITATOR_NEEDED_YES && openEnrlment.Materials_Needed__c==UtilConstants.NO_PROMO_OR_COLLATERAL_NEEDED  && openEnrlment.Facilitator_Being_Recruited__c==true 
                        && openEnrlment.Facilitator_Secured__c==false && openEnrlment.Unable_to_secure_facilitator__c==false && openEnrlment.Waiting_on_Feedback__c==false && openEnrlment.Feedback_Not_Received_Within_14_Days__c==false 
                        && openEnrlment.Facilitator_Feedback_Received__c==false && openEnrlment.Materials_Order_On_Standby__c==false && openEnrlment.Materials_Order_placed__c==false && openEnrlment.Materials_Delivered__c==false 
                        && openEnrlment.Meeting_Cancelled__c==false && openEnrlment.Submit__c==true ){
                        
                            openEnrlment.Meeting_Stage__c=UtilConstants.STAGE_INPROCESS;
                            openEnrlment.Meeting_Status__c=UtilConstants.STATUS_INPROCESS_FAC_BEING_RECR; 
                
                }else if((( openEnrlment.Date__c!=null) && openEnrlment.Date__c> System.TODAY()+13 &&  openEnrlment.RUSH__c==true )&& (openEnrlment.Meeting_Stage__c=='Submitted - Rush' || openEnrlment.Meeting_Stage__c=='Updated - Rush')){
                        
                        openEnrlment.Meeting_Stage__c=UtilConstants.STATUS_SUBMITTED;
                        openEnrlment.RUSH__c =false; 
                        
                }else if(openEnrlment.Recruitment_of_Facilitator_Needed__c==UtilConstants.REC_OF_FACILITATOR_NEEDED_YES && (openEnrlment.Materials_Needed__c==UtilConstants.PROMO_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.COLLATERAL_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.PROMO_AND_COLLATERAL_NEEDED ) 
                        && openEnrlment.Facilitator_Being_Recruited__c==false && openEnrlment.Facilitator_Secured__c==false && openEnrlment.Unable_to_secure_facilitator__c==true && openEnrlment.Waiting_on_Feedback__c==false && openEnrlment.Feedback_Not_Received_Within_14_Days__c==false 
                        && openEnrlment.Facilitator_Feedback_Received__c==false && openEnrlment.Materials_Order_On_Standby__c==false && openEnrlment.Materials_Order_placed__c==true && openEnrlment.Materials_Delivered__c==true 
                        && openEnrlment.Meeting_Cancelled__c==false && openEnrlment.Submit__c==true ){
                                            
                            openEnrlment.Meeting_Stage__c=UtilConstants.STAGE_COMPLETE;
                            openEnrlment.Meeting_Status__c=UtilConstants.STATUS_COMPLETED_UNABLE_TO_SEC_FAC_AND_MAT_DELIVERED; 
                
                }else if(openEnrlment.Recruitment_of_Facilitator_Needed__c==UtilConstants.REC_OF_FACILITATOR_NEEDED_YES && (openEnrlment.Materials_Needed__c==UtilConstants.PROMO_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.COLLATERAL_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.PROMO_AND_COLLATERAL_NEEDED ) 
                        && openEnrlment.Facilitator_Being_Recruited__c==false && openEnrlment.Facilitator_Secured__c==false && openEnrlment.Unable_to_secure_facilitator__c==true && openEnrlment.Waiting_on_Feedback__c==false && openEnrlment.Feedback_Not_Received_Within_14_Days__c==false 
                        && openEnrlment.Facilitator_Feedback_Received__c==false && openEnrlment.Materials_Order_On_Standby__c==false && openEnrlment.Materials_Order_placed__c==true && openEnrlment.Materials_Delivered__c==false 
                        && openEnrlment.Meeting_Cancelled__c==false && openEnrlment.Submit__c==true ){
                        
                            openEnrlment.Meeting_Stage__c=UtilConstants.STAGE_INPROCESS;
                            openEnrlment.Meeting_Status__c=UtilConstants.STATUS_INPROCESS_UNABLE_TO_SEC_FAC_ORDER_PLACED; 
                
                }else if(openEnrlment.Recruitment_of_Facilitator_Needed__c==UtilConstants.REC_OF_FACILITATOR_NEEDED_YES && (openEnrlment.Materials_Needed__c==UtilConstants.PROMO_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.COLLATERAL_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.PROMO_AND_COLLATERAL_NEEDED ) 
                        && openEnrlment.Facilitator_Being_Recruited__c==false && openEnrlment.Facilitator_Secured__c==true && openEnrlment.Unable_to_secure_facilitator__c==false && openEnrlment.Waiting_on_Feedback__c==false && openEnrlment.Feedback_Not_Received_Within_14_Days__c==false 
                        && openEnrlment.Facilitator_Feedback_Received__c==true && openEnrlment.Materials_Order_On_Standby__c==false && openEnrlment.Materials_Order_placed__c==true && openEnrlment.Materials_Delivered__c==true 
                        && openEnrlment.Meeting_Cancelled__c==false && openEnrlment.Submit__c==true ){
                                            
                            openEnrlment.Meeting_Stage__c=UtilConstants.STAGE_COMPLETE;
                            openEnrlment.Meeting_Status__c=UtilConstants.STATUS_COMPLETED_FAC_SEC_AND_MAT_DEL_AND_MEET_FEED_REC; 
                
                }else if(openEnrlment.Recruitment_of_Facilitator_Needed__c==UtilConstants.REC_OF_FACILITATOR_NEEDED_YES && (openEnrlment.Materials_Needed__c==UtilConstants.PROMO_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.COLLATERAL_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.PROMO_AND_COLLATERAL_NEEDED ) 
                        && openEnrlment.Facilitator_Being_Recruited__c==false && openEnrlment.Facilitator_Secured__c==true && openEnrlment.Unable_to_secure_facilitator__c==false && openEnrlment.Waiting_on_Feedback__c==false && openEnrlment.Feedback_Not_Received_Within_14_Days__c==true 
                        && openEnrlment.Facilitator_Feedback_Received__c==false && openEnrlment.Materials_Order_On_Standby__c==false && openEnrlment.Materials_Order_placed__c==true && openEnrlment.Materials_Delivered__c==true 
                        && openEnrlment.Meeting_Cancelled__c==false && openEnrlment.Submit__c==true ){
                                            
                            openEnrlment.Meeting_Stage__c=UtilConstants.STAGE_COMPLETE;
                            openEnrlment.Meeting_Status__c=UtilConstants.STATUS_COMPLETED_FAC_SEC_AND_MAT_DEL_AND_FEED_NOT_REC_WITHIN_14_DAYS; 
                
                }else if(openEnrlment.Recruitment_of_Facilitator_Needed__c==UtilConstants.REC_OF_FACILITATOR_NEEDED_YES && (openEnrlment.Materials_Needed__c==UtilConstants.PROMO_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.COLLATERAL_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.PROMO_AND_COLLATERAL_NEEDED ) 
                        && openEnrlment.Facilitator_Being_Recruited__c==false && openEnrlment.Facilitator_Secured__c==true && openEnrlment.Unable_to_secure_facilitator__c==false && openEnrlment.Waiting_on_Feedback__c==true && openEnrlment.Feedback_Not_Received_Within_14_Days__c==false 
                        && openEnrlment.Facilitator_Feedback_Received__c==false && openEnrlment.Materials_Order_On_Standby__c==false && openEnrlment.Materials_Order_placed__c==true && openEnrlment.Materials_Delivered__c==true 
                        && openEnrlment.Meeting_Cancelled__c==false && openEnrlment.Submit__c==true ){
                        
                            openEnrlment.Meeting_Stage__c=UtilConstants.STAGE_INPROCESS;
                            openEnrlment.Meeting_Status__c=UtilConstants.STATUS_INPROCESS_FAC_SEC_AND_MAT_DEL_AND_WAIT_ON_FEED; 
                
                }else if(openEnrlment.Recruitment_of_Facilitator_Needed__c==UtilConstants.REC_OF_FACILITATOR_NEEDED_YES && (openEnrlment.Materials_Needed__c==UtilConstants.PROMO_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.COLLATERAL_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.PROMO_AND_COLLATERAL_NEEDED ) 
                        && openEnrlment.Facilitator_Being_Recruited__c==false && openEnrlment.Facilitator_Secured__c==false && openEnrlment.Unable_to_secure_facilitator__c==true && openEnrlment.Waiting_on_Feedback__c==false && openEnrlment.Feedback_Not_Received_Within_14_Days__c==false 
                        && openEnrlment.Facilitator_Feedback_Received__c==false && openEnrlment.Materials_Order_On_Standby__c==true && openEnrlment.Materials_Order_placed__c==false && openEnrlment.Materials_Delivered__c==false 
                        && openEnrlment.Meeting_Cancelled__c==false && openEnrlment.Submit__c==true ){
                        
                            openEnrlment.Meeting_Stage__c=UtilConstants.STAGE_INPROCESS;
                            openEnrlment.Meeting_Status__c=UtilConstants.STATUS_INPROCESS_UNABLE_TO_SEC_FAC_ORDER_ON_STANDBY; 
                
                }else if(openEnrlment.Recruitment_of_Facilitator_Needed__c==UtilConstants.REC_OF_FACILITATOR_NEEDED_YES && (openEnrlment.Materials_Needed__c==UtilConstants.PROMO_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.COLLATERAL_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.PROMO_AND_COLLATERAL_NEEDED ) 
                        && openEnrlment.Facilitator_Being_Recruited__c==false && openEnrlment.Facilitator_Secured__c==true && openEnrlment.Unable_to_secure_facilitator__c==false && openEnrlment.Waiting_on_Feedback__c==true && openEnrlment.Feedback_Not_Received_Within_14_Days__c==false 
                        && openEnrlment.Facilitator_Feedback_Received__c==false && openEnrlment.Materials_Order_On_Standby__c==false && openEnrlment.Materials_Order_placed__c==true && openEnrlment.Materials_Delivered__c==false 
                        && openEnrlment.Meeting_Cancelled__c==false && openEnrlment.Submit__c==true ){
                            
                            openEnrlment.Meeting_Stage__c=UtilConstants.STAGE_INPROCESS;
                            openEnrlment.Meeting_Status__c=UtilConstants.STATUS_INPROCESS_FAC_SEC_AND_ORDER_PLACED_AND_WAIT_ON_FEED; 
                
                }else if(openEnrlment.Recruitment_of_Facilitator_Needed__c==UtilConstants.REC_OF_FACILITATOR_NEEDED_YES && openEnrlment.Materials_Needed__c==UtilConstants.NO_PROMO_OR_COLLATERAL_NEEDED && openEnrlment.Facilitator_Being_Recruited__c==false 
                        && openEnrlment.Facilitator_Secured__c==false && openEnrlment.Unable_to_secure_facilitator__c==true && openEnrlment.Waiting_on_Feedback__c==false && openEnrlment.Feedback_Not_Received_Within_14_Days__c==false 
                        && openEnrlment.Facilitator_Feedback_Received__c==false && openEnrlment.Materials_Order_On_Standby__c==false && openEnrlment.Materials_Order_placed__c==false && openEnrlment.Materials_Delivered__c==false 
                        && openEnrlment.Meeting_Cancelled__c==false && openEnrlment.Submit__c==true ){
                                
                            openEnrlment.Meeting_Stage__c=UtilConstants.STAGE_COMPLETE;
                            openEnrlment.Meeting_Status__c=UtilConstants.STATUS_COMPLETED_UNABLE_TO_SEC_FAC; 
                
                }else if(openEnrlment.Recruitment_of_Facilitator_Needed__c==UtilConstants.REC_OF_FACILITATOR_NEEDED_YES && (openEnrlment.Materials_Needed__c==UtilConstants.PROMO_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.COLLATERAL_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.PROMO_AND_COLLATERAL_NEEDED ) 
                        && openEnrlment.Facilitator_Being_Recruited__c==true && openEnrlment.Facilitator_Secured__c==false && openEnrlment.Unable_to_secure_facilitator__c==false && openEnrlment.Waiting_on_Feedback__c==false && openEnrlment.Feedback_Not_Received_Within_14_Days__c==false 
                        && openEnrlment.Facilitator_Feedback_Received__c==false && openEnrlment.Materials_Order_On_Standby__c==true && openEnrlment.Materials_Order_placed__c==false && openEnrlment.Materials_Delivered__c==false 
                        && openEnrlment.Meeting_Cancelled__c==false && openEnrlment.Submit__c==true ){
                        
                            openEnrlment.Meeting_Stage__c=UtilConstants.STAGE_INPROCESS;
                            openEnrlment.Meeting_Status__c=UtilConstants.STATUS_INPROCESS_FAC_BEING_RECR_AND_ORDER_ON_STANDBY; 
                
                }else if(openEnrlment.Recruitment_of_Facilitator_Needed__c==UtilConstants.REC_OF_FACILITATOR_NEEDED_YES && (openEnrlment.Materials_Needed__c==UtilConstants.PROMO_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.COLLATERAL_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.PROMO_AND_COLLATERAL_NEEDED ) 
                        && openEnrlment.Facilitator_Being_Recruited__c==true && openEnrlment.Facilitator_Secured__c==false && openEnrlment.Unable_to_secure_facilitator__c==false && openEnrlment.Waiting_on_Feedback__c==false && openEnrlment.Feedback_Not_Received_Within_14_Days__c==false 
                        && openEnrlment.Facilitator_Feedback_Received__c==false && openEnrlment.Materials_Order_On_Standby__c==false && openEnrlment.Materials_Order_placed__c==true && openEnrlment.Materials_Delivered__c==true 
                        && openEnrlment.Meeting_Cancelled__c==false && openEnrlment.Submit__c==true ){
                        
                            openEnrlment.Meeting_Stage__c=UtilConstants.STAGE_INPROCESS;
                            openEnrlment.Meeting_Status__c=UtilConstants.STATUS_INPROCESS_FAC_BEING_RECR_AND_MAT_DELIVERED; 
                
                }else if(openEnrlment.Recruitment_of_Facilitator_Needed__c==UtilConstants.REC_OF_FACILITATOR_NEEDED_YES && (openEnrlment.Materials_Needed__c==UtilConstants.PROMO_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.COLLATERAL_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.PROMO_AND_COLLATERAL_NEEDED ) 
                        && openEnrlment.Facilitator_Being_Recruited__c==true && openEnrlment.Facilitator_Secured__c==false && openEnrlment.Unable_to_secure_facilitator__c==false && openEnrlment.Waiting_on_Feedback__c==false && openEnrlment.Feedback_Not_Received_Within_14_Days__c==false 
                        && openEnrlment.Facilitator_Feedback_Received__c==false && openEnrlment.Materials_Order_On_Standby__c==false && openEnrlment.Materials_Order_placed__c==true && openEnrlment.Materials_Delivered__c==false 
                        && openEnrlment.Meeting_Cancelled__c==false && openEnrlment.Submit__c==true ){
                        
                            openEnrlment.Meeting_Stage__c=UtilConstants.STAGE_INPROCESS;
                            openEnrlment.Meeting_Status__c=UtilConstants.STATUS_INPROCESS_FAC_BEING_RECR_AND_ORDER_PLACED; 
                
                }else if(openEnrlment.Recruitment_of_Facilitator_Needed__c==UtilConstants.REC_OF_FACILITATOR_NEEDED_YES && (openEnrlment.Materials_Needed__c==UtilConstants.PROMO_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.COLLATERAL_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.PROMO_AND_COLLATERAL_NEEDED ) 
                        && openEnrlment.Facilitator_Being_Recruited__c==false && openEnrlment.Facilitator_Secured__c==true && openEnrlment.Unable_to_secure_facilitator__c==false && openEnrlment.Waiting_on_Feedback__c==true && openEnrlment.Feedback_Not_Received_Within_14_Days__c==false 
                        && openEnrlment.Facilitator_Feedback_Received__c==false && openEnrlment.Materials_Order_On_Standby__c==true && openEnrlment.Materials_Order_placed__c==false && openEnrlment.Materials_Delivered__c==false 
                        && openEnrlment.Meeting_Cancelled__c==false && openEnrlment.Submit__c==true ){
                        
                            openEnrlment.Meeting_Stage__c=UtilConstants.STAGE_INPROCESS;
                            openEnrlment.Meeting_Status__c=UtilConstants.STATUS_INPROCESS_FAC_SEC_AND_WAIT_ON_FEED_AND_ORDER_ON_STANDBY; 
                
                }else if(openEnrlment.Recruitment_of_Facilitator_Needed__c==UtilConstants.REC_OF_FACILITATOR_NEEDED_NO && (openEnrlment.Materials_Needed__c==UtilConstants.PROMO_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.COLLATERAL_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.PROMO_AND_COLLATERAL_NEEDED ) 
                        && openEnrlment.Facilitator_Being_Recruited__c==false && openEnrlment.Facilitator_Secured__c==false && openEnrlment.Unable_to_secure_facilitator__c==false && openEnrlment.Waiting_on_Feedback__c==false && openEnrlment.Feedback_Not_Received_Within_14_Days__c==false 
                        && openEnrlment.Facilitator_Feedback_Received__c==false && openEnrlment.Materials_Order_On_Standby__c==true && openEnrlment.Materials_Order_placed__c==false && openEnrlment.Materials_Delivered__c==false 
                        && openEnrlment.Meeting_Cancelled__c==false && openEnrlment.Submit__c==true ){
                                                 
                            openEnrlment.Meeting_Stage__c=UtilConstants.STAGE_INPROCESS;
                            openEnrlment.Meeting_Status__c=UtilConstants.STATUS_INPROCESS_ORDER_ON_STANDBY; 
                
                }else if(openEnrlment.Recruitment_of_Facilitator_Needed__c==UtilConstants.REC_OF_FACILITATOR_NEEDED_NO && (openEnrlment.Materials_Needed__c==UtilConstants.PROMO_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.COLLATERAL_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.PROMO_AND_COLLATERAL_NEEDED ) 
                        && openEnrlment.Facilitator_Being_Recruited__c==false && openEnrlment.Facilitator_Secured__c==false && openEnrlment.Unable_to_secure_facilitator__c==false && openEnrlment.Waiting_on_Feedback__c==false && openEnrlment.Feedback_Not_Received_Within_14_Days__c==false 
                        && openEnrlment.Facilitator_Feedback_Received__c==false && openEnrlment.Materials_Order_On_Standby__c==false && openEnrlment.Materials_Order_placed__c==true && openEnrlment.Materials_Delivered__c==true 
                        && openEnrlment.Meeting_Cancelled__c==false && openEnrlment.Submit__c==true ){
                                                
                           openEnrlment.Meeting_Stage__c=UtilConstants.STAGE_COMPLETE;
                            openEnrlment.Meeting_Status__c=UtilConstants.STATUS_COMPLETED_MAT_DELIVERED; 
                
                }else if(openEnrlment.Recruitment_of_Facilitator_Needed__c==UtilConstants.REC_OF_FACILITATOR_NEEDED_NO && (openEnrlment.Materials_Needed__c==UtilConstants.PROMO_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.COLLATERAL_ONLY_NEEDED || openEnrlment.Materials_Needed__c==UtilConstants.PROMO_AND_COLLATERAL_NEEDED ) 
                        && openEnrlment.Facilitator_Being_Recruited__c==false && openEnrlment.Facilitator_Secured__c==false && openEnrlment.Unable_to_secure_facilitator__c==false && openEnrlment.Waiting_on_Feedback__c==false && openEnrlment.Feedback_Not_Received_Within_14_Days__c==false 
                        && openEnrlment.Facilitator_Feedback_Received__c==false && openEnrlment.Materials_Order_On_Standby__c==false && openEnrlment.Materials_Order_placed__c==true && openEnrlment.Materials_Delivered__c==false 
                        && openEnrlment.Meeting_Cancelled__c==false && openEnrlment.Submit__c==true ){
                            
                            openEnrlment.Meeting_Stage__c=UtilConstants.STAGE_INPROCESS;
                            openEnrlment.Meeting_Status__c=UtilConstants.STATUS_INPROCESS_ORDER_PLACED; 
                }

                System.debug('openEnrlment.Meeting_Stage__c'+openEnrlment.Meeting_Stage__c); 
            }   
            }
            
           
        } 
        
       
    }