objects/SFDC_Volunteer_Event__c.object
<CustomObject>
    <description>Used to manage and track vounteer events</description>
    <fields>
        <fullName>Meeting_City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Meeting City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meeting_Comments_History__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Meeting Comments History</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Meeting_Comments__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter specific notes related to this mtg record;  for Updates please include what new info. –ei. new meeting date ; new time sessions; new address details; new contact name/ph</inlineHelpText>
        <label>Meeting Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Meeting_State__c</fullName>
        <label>Meeting State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Meeting_Street__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Meeting Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Meeting_Zip_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Meeting Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Open Enrollment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Enrollment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OpenEnrollmentTriggerHandler.cls
/*************************************************************************************
Version     : 1.0 
@Author: Rahmath
Function    : Trigger Handler for Open enrollment object
@description :Trigger Handler for Open enrollment object
*************************************************************************************/
public with Sharing class OpenEnrollmentTriggerHandler {
        /*
        * @description updateMeetingCommHistory method
        * @param newRecords
        * @param oldMap
        */
    
    public static void updateMeetingCommHistory(List<SFDC_Volunteer_Event__c> newRecords, Map<Id, SFDC_Volunteer_Event__c> oldMap){
        
        String sComments = null;
        DateTime myDateTime = System.now();
        String formatted = myDateTime.formatGMT('MM-dd-yyyy\' - \'HH:mm:ss');
        
        for(SFDC_Volunteer_Event__c objSVE : newRecords){
            
            SFDC_Volunteer_Event__c objOldRec = oldMap.get(objSVE.id);            
            if(objSVE.Meeting_Comments__c== objOldRec.Meeting_Comments__c){
              continue;  
            } 
            sComments = objOldRec.Meeting_Comments__c + ' - ' + Userinfo.getFirstName() + ' ' + Userinfo.getLastName() + ' - ' + formatted;
            
            if(String.isBlank(objSVE.Meeting_Comments_History__c)){
              objSVE.Meeting_Comments_History__c  = sComments;    
            }else{
              objSVE.Meeting_Comments_History__c  = sComments + '\n' + objSVE.Meeting_Comments_History__c;  
            }
                
        }
    }
    
    ///Added - DK - 17-Jul
    

        /*
        * @description verifyLocation method
        * @param newRecords
        * @param oldRecords
        * @return List<SFDC_Volunteer_Event__c>
        */
    
    
  public static List<SFDC_Volunteer_Event__c> verifyLocation(List<SFDC_Volunteer_Event__c> newRecords, Map<Id, SFDC_Volunteer_Event__c> oldRecords){

    List<SFDC_Volunteer_Event__c> updatedAddresses = new List<SFDC_Volunteer_Event__c>();
    for(SFDC_Volunteer_Event__c event : newRecords){
      if(isAddressChanged(event, oldRecords.get(event.Id))){
        updatedAddresses.add(event);
      }
    }

    return updatedAddresses;
  }
        /**
        * @description updateChangedAddresses method
        * @param updatedMeetings
        */
  
    public static void updateChangedAddresses(List<SFDC_Volunteer_Event__c> updatedMeetings) {
    List<SFDC_Volunteer_Event__c> meetingsToUpdateWithLocations = new List<SFDC_Volunteer_Event__c>();

    TravelResponseService.sendLocationRequest(updatedMeetings);
  }
        /*
        * @description isAddressChanged method
        * @param newMeeting
        * @param oldMeeting
        * @return boolean
        */
    
    
  public static boolean isAddressChanged(SFDC_Volunteer_Event__c newMeeting, SFDC_Volunteer_Event__c oldMeeting){
    return ((newMeeting.Location__latitude__s == null && newMeeting.Location__longitude__s == null) || newMeeting.Meeting_Street__c != oldMeeting.Meeting_Street__c || newMeeting.Meeting_City__c != oldMeeting.Meeting_City__c || newMeeting.Meeting_State__c != oldMeeting.Meeting_State__c || newMeeting.Meeting_Zip_Code__c != oldMeeting.Meeting_Zip_Code__c);
  }
        /*
        * @description checkUpdateCount method
        * @param newRecords
        * @return Boolean
        */
    
    
  public static Boolean checkUpdateCount(List<SFDC_Volunteer_Event__c> newRecords) {
    return (newRecords.size() > 100);
  }
  
   
    
}