objects/WeeklyLeadConversionReport__c.object
<CustomObject>
    <description>Contains the lead converesion report by week</description>
    <fields>
        <fullName>CurrentWeekAmount__c</fullName>
        <description>Stores current week amount.</description>
        <label>CurrentWeekAmount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DateOfTheStage__c</fullName>
        <description>Contains when the particular stage was created.</description>
        <label>DateOfTheStage</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PreviousWeekAmount__c</fullName>
        <description>Stores amount of the stage for previous week</description>
        <label>PreviousWeekAmount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>WeeklyLeadConversionReport</label>
    <nameField>
        <label>WeeklyLeadConversionStage</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeeklyLeadConversionReports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchCLS_WeaklyLeadConversion_Test.cls
@isTest
public class BatchCLS_WeaklyLeadConversion_Test {
    @isTest(SeeAllData='true')
    public static void LeadConversionReportData_Method(){
        
        Opportunity opp = new Opportunity(Name='ApexTestOpp', StageName='stage',Probability = 95, CloseDate=system.today(),Amount = 950000);
        insert opp;
        
        WeeklyLeadConversionReport__c leadConversionInfo = new WeeklyLeadConversionReport__c(Name = 'stage',DateOfTheStage__c =Date.newInstance(2016, 12, 9) ,CurrentWeekAmount__c = 95000,PreviousWeekAmount__c= 53433);
        
        insert leadConversionInfo;
        //Test.setCreatedDate(leadConversionInfo.Id, (Date.today() -1).tostartOfMonth());
        System.debug(leadConversionInfo.CreatedDate);
        Test.startTest();
        BatchCLS_WeaklyLeadConversion WeeklyleadConversion = new BatchCLS_WeaklyLeadConversion();
        Database.executeBatch(WeeklyleadConversion);
        Test.stopTest();
        
    }
}