src/objects/Account.object
<CustomObject>
</CustomObject>

folder1/folder2/folder3/objects/Account.object
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Open_Enrollment_Meetings__c.object
<CustomObject>
    <description>This object is a container for all individual OE Meetings.  An Account may be associated to 0 to many Open Enrollment Meeting (Groupings).</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the account for which the OE meetings will be recorded.</description>
        <inlineHelpText>Select an account if this set of meetings is related to an account in Salesforce.com.</inlineHelpText>
        <label>Account Legal Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Open Enrollment Meetings</relationshipLabel>
        <relationshipName>Open_Enrollment_Meetings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Anthem_Entity__c</fullName>
        <formula>TEXT(Account__r.Anthem_Entity__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Anthem Entity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Drivers_Issues_Risks__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Use this space to list out any notable Client Drivers, Issues / Risks, Talking Points, and Division Names.</inlineHelpText>
        <label>Client Drivers, Issues / Risks</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Dress_Code_for_Event__c</fullName>
        <label>Dress Code for Event</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business Casual</fullName>
                </value>
                <value>
                    <fullName>Business Formal</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OE_Coordinator_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is from the Facilitator account.  It will be populated by a workflow.  The OE Coordinator is now a Facilitator role on the facilitator account so they can manage who the facilitator will be should there be personnell changes</description>
        <inlineHelpText>This field will be populated when you save the record.  There is no need to enter the OE Coordinator..</inlineHelpText>
        <label>OE Coordinator</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Facilitator_Type__c</field>
                <operation>equals</operation>
                <value>OE Coordinator</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Open Enrollment Meetings</relationshipLabel>
        <relationshipName>Open_Enrollment_Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <description>The Plan Type for the meetings group.</description>
        <inlineHelpText>Select the Product offering for this group of meetings.</inlineHelpText>
        <label>Plan Type</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>MED     CDHP- HIA</fullName>
                </value>
                <value>
                    <fullName>MED     CDHP - HRA</fullName>
                </value>
                <value>
                    <fullName>MED     CDHP -HSA</fullName>
                    <label>MED     CDHP - HSA</label>
                </value>
                <value>
                    <fullName>MED     POS</fullName>
                </value>
                <value>
                    <fullName>MED     PPO</fullName>
                </value>
                <value>
                    <fullName>MED     EPO</fullName>
                </value>
                <value>
                    <fullName>MED     HMO</fullName>
                </value>
                <value>
                    <fullName>MED     JAA</fullName>
                </value>
                <value>
                    <fullName>MED     LiveHealth Online</fullName>
                </value>
                <value>
                    <fullName>MED     Engage</fullName>
                </value>
                <value>
                    <fullName>CA      Elements Choice</fullName>
                </value>
                <value>
                    <fullName>CA      Elements Choice EQ</fullName>
                </value>
                <value>
                    <fullName>CA      First Impressions</fullName>
                </value>
                <value>
                    <fullName>CA      SIMNSA</fullName>
                </value>
                <value>
                    <fullName>CA      Transition Assistance</fullName>
                </value>
                <value>
                    <fullName>CA      Vivity</fullName>
                </value>
                <value>
                    <fullName>Group Retiree   MA HMO</fullName>
                </value>
                <value>
                    <fullName>Group Retiree   MAPD-HMO</fullName>
                </value>
                <value>
                    <fullName>Group Retiree   MAPD- PPO</fullName>
                </value>
                <value>
                    <fullName>Group Retiree   MA PPO</fullName>
                </value>
                <value>
                    <fullName>Group Retiree   PDP</fullName>
                </value>
                <value>
                    <fullName>HW – Group Retiree - Silver Sneakers</fullName>
                </value>
                <value>
                    <fullName>HW      24/7 Nurseline</fullName>
                </value>
                <value>
                    <fullName>HW      AIM</fullName>
                </value>
                <value>
                    <fullName>HW      Anthem Health Guide</fullName>
                </value>
                <value>
                    <fullName>HW      Anthem Health Rewards</fullName>
                </value>
                <value>
                    <fullName>HW      Anthem Mobile Health</fullName>
                </value>
                <value>
                    <fullName>HW      Complex Care</fullName>
                </value>
                <value>
                    <fullName>HW      ConditionCare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Open Enrollment Meetings</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>OE Meeting Grouping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Enrollment Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDC_Volunteer_Event__c.object
<CustomObject>
    <description>Used to manage and track vounteer events</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Open Enrollment</relationshipLabel>
        <relationshipName>Open_Enrollment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Anthem_Entity__c</fullName>
        <formula>OE_Grouping__r.Anthem_Entity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Anthem Entity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Meeting Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Meeting_Stage__c</fullName>
        <description>This field shows where the meeting is in the entry process.</description>
        <inlineHelpText>Change status to SUBMITTED when all fields have been entered and the meeting is ready for validation and submission to the OE Coordinator.</inlineHelpText>
        <label>Meeting Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DRAFT</fullName>
                    <default>true</default>
                    <label>DRAFT</label>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>SUBMITTED</fullName>
                </value>
                <value>
                    <fullName>Submitted - Rush</fullName>
                </value>
                <value>
                    <fullName>UPDATED</fullName>
                </value>
                <value>
                    <fullName>Updated - Rush</fullName>
                </value>
                <value>
                    <fullName>COMPLETE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Meeting_Type__c</fullName>
        <label>Meeting Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Benefit Fair</fullName>
                </value>
                <value>
                    <fullName>Conference Call</fullName>
                </value>
                <value>
                    <fullName>Health Fair</fullName>
                </value>
                <value>
                    <fullName>PowerPoint w/ VO  {PP with VO}</fullName>
                    <label>PowerPoint with Voiceover</label>
                </value>
                <value>
                    <fullName>Presentation</fullName>
                </value>
                <value>
                    <fullName>Q &amp; A</fullName>
                </value>
                <value>
                    <fullName>Supplies Only</fullName>
                </value>
                <value>
                    <fullName>Virtual (Webinar)</fullName>
                </value>
                <value>
                    <fullName>OE Kit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OE_Coordinator_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The lookup for the OE Coordinator so that email alerts can be sent when meetings are submitted or changed</description>
        <inlineHelpText>Please select your Open Enrollment Coordinator - For Central and South West - Colleen Douma, For North East - Colleen Jacobs, For West - Bethany Snee.</inlineHelpText>
        <label>OE Coordinator</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Facilitator_Type__c</field>
                <operation>equals</operation>
                <value>OE Coordinator</value>
            </filterItems>
            <infoMessage>This field will be populated after save</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Open Enrollment (OE Coordinator)</relationshipLabel>
        <relationshipName>Open_Enrollment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OE_Grouping__c</fullName>
        <description>The parent link.</description>
        <inlineHelpText>This link will take you back to the Group Meeting record.</inlineHelpText>
        <label>Meetings Grouping</label>
        <referenceTo>Open_Enrollment_Meetings__c</referenceTo>
        <relationshipLabel>Open Enrollment</relationshipLabel>
        <relationshipName>Open_Enrollment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Recruitment_of_Facilitator_Needed__c</fullName>
        <description>AM checks this if they will not be attending or if they don&apos;t already have a facilitator lined up.</description>
        <inlineHelpText>If Yes Open Enrollment Team will seek coverage.</inlineHelpText>
        <label>Facilitator Needs to be Recruited</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Open Enrollment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Enrollment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SFDC_Volunteer_Participant__c.object
<CustomObject>
    <description>A junction object used for linking Volunteer Events to a participant</description>
    <fields>
        <fullName>Facilitator_Type__c</fullName>
        <formula>TEXT(OE_Ambassador_Volunteer__r.Facilitator_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Facilitator Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Volunteer_Event__c</fullName>
        <label>Meeting Name</label>
        <referenceTo>SFDC_Volunteer_Event__c</referenceTo>
        <relationshipLabel>OE Ambassador Volunteers</relationshipLabel>
        <relationshipName>R00N30000001WZmFEAW</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>OE Ambassador Volunteers</label>
    <nameField>
        <displayFormat>Volunteer_ID {0000}</displayFormat>
        <label>Volunteer Participant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OE Ambassador Volunteers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OEAmbVolCountTallyFieldsTest.cls
/**************************************************************************************
@description : Test Class for OEAmbVolCountTallyFields
@Author               : X-men Offshore
US                        : PRDCRM-30730 . Modified Test class as part of PRDCRM-41975
*************************************************************************************/

@isTest
public class OEAmbVolCountTallyFieldsTest {
    public static final String COORDINATOR_EMAIL = 'coordinator@test.com';
    
    @testSetup
    static void setupTestData(){
        Test.setMock(HttpCalloutMock.class, New MockBingTravelResponse());
        
        Id conrtID = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Facilitator Contact').getRecordTypeId();
        Id accrtID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Prospect').getRecordTypeId();
        
        
        Account accRec = new Account();
        accRec.Name = 'Open Enrollment';
        accRec.Anthem_Entity__c = 'National Accounts';
        accRec.Region__c = 'Central';
        insert accRec;
        
        Account acc = (Account)TestFactory.createSObject(new Account(name='Open Enrollment'), true);
        
         List<Contact> ambassadors = new List<Contact>();

 
       Contact ambassador = 
        (Contact)TestFactory.createSObject(new Contact(accountId = acc.Id, 
          Facilitator_Type__c = VolunteerParticipantEmailServiceImpl.OE_AMBASSADOR_TYPE));
          
          insert ambassador;
          
        Contact coordinator = 
        (Contact)TestFactory.createSObject(new Contact(accountId = acc.Id, email = COORDINATOR_EMAIL,
        Facilitator_Type__c = VolunteerParticipantEmailServiceImpl.OE_COORDINATOR_TYPE), true); 
        
        //Insert contact records
        Contact conRec = new Contact();
        conRec.recordtypeid = UtilConstants.Contact_RecordType_ID;
        conRec.AccountId = accRec.id;
        conRec.LastName = 'Test123';
        conRec.OE_Amb_No_Thanks_Current_Year_Tally__c = -1;
        conRec.OE_Amb_Selected_Current_Year_Tally__c = -1;
        conRec.Facilitator_Type__c='OE Ambassador';
        conRec.Email='test22@test.com';
        insert conRec;
        
        Contact conRec1 = new Contact();
        conRec.recordtypeid = UtilConstants.Contact_RecordType_ID;
        conRec1.AccountId = accRec.id;
        conRec1.LastName = 'Test123';
        conRec1.OE_Amb_No_Thanks_Current_Year_Tally__c = NULL;
        conRec1.OE_Amb_Selected_Current_Year_Tally__c = NULL;
        conRec1.Facilitator_Type__c='OE Ambassador';
        conRec1.Email='test11@test.com';
        insert conRec1;
        
        Contact conRec5 = new Contact();
        conRec5.recordtypeid = UtilConstants.Contact_RecordType_ID;
        conRec5.AccountId = accRec.id;
        conRec5.LastName = 'Test123';
        conRec5.OE_Amb_No_Thanks_Current_Year_Tally__c = NULL;
        conRec5.OE_Amb_Selected_Current_Year_Tally__c = NULL;
        conRec5.Facilitator_Type__c='OE Ambassador';
        conRec5.Email='test55@test.com';
        insert conRec5;
        
        
        Contact conRec6=new Contact();
        conRec6.lastname='Test Central';
        conRec6.firstname='test';
        conRec6.AccountId=accRec.Id;
        conRec6.RecordTypeID=Schema.SobjectType.Contact.getRecordTypeInfosByName().get('Facilitator Contact').getRecordTypeId();
        conRec6.Facilitator_Type__c='OE Coordinator';
        conRec6.Region_Location__c='Central';
        conRec6.Email='test@test.com';
        conRec6.Active__c=true;
        insert conRec6;
        
        //Insert OE meeting record
        Open_Enrollment_Meetings__c oemeetingRec = new Open_Enrollment_Meetings__c();
        oemeetingRec.Name = 'Test123';
        oemeetingRec.Account__c = accRec.id;
        oemeetingRec.Client_Drivers_Issues_Risks__c = 'Test tally fields';
        oemeetingRec.Dress_Code_for_Event__c = UtilConstants.Dress_Code_for_Event;
        oemeetingRec.Plan_Type__c = UtilConstants.Plan_Type;
        oemeetingRec.OE_Coordinator_Contact__c=conRec6.Id;
        insert oemeetingRec;
        
        //Insert OE record
        SFDC_Volunteer_Event__c oeRec = new SFDC_Volunteer_Event__c();
        oeRec.Name = 'Test123';
        oeRec.Account__c = accRec.Id;
        oeRec.OE_Grouping__c = oemeetingRec.Id;
        oeRec.Meeting_Type__c = UtilConstants.Meeting_Type;
        oeRec.Date__c = System.Today();
        oeRec.Recruitment_of_Facilitator_Needed__c = 'No';
        oeRec.Meeting_Stage__c='DRAFT';
        oeRec.Meeting_Status__c='NEW REQUEST';
        oeRec.OE_Coordinator_Contact__c=conRec6.Id;
        insert oeRec;
        
       
        Open_Enrollment_Meetings__c meeting = 
        (Open_Enrollment_Meetings__c)TestFactory.createSObject(
        new Open_Enrollment_Meetings__c(account__c = acc.Id, source__c = 'Central', Plan_Type__c='MED CDHP- HIA',
                  OE_Coordinator_Contact__c = coordinator.Id), true);

        SFDC_Volunteer_Event__c event = 
        (SFDC_Volunteer_Event__c)TestFactory.createSObject(
        new SFDC_Volunteer_Event__c(OE_Grouping__c = meeting.Id, name = 'Test Event', bilingual__c = 'No', Buddy_Program_Eligible__c = FALSE,Meeting_Type__c='Benefit Fair',Recruitment_of_Facilitator_Needed__c='Yes',
        meeting_city__c = 'Poway', meeting_state__c = 'CA', Date__c = system.today()), true);                
        
       List<SFDC_Volunteer_Participant__c> participants = new List<SFDC_Volunteer_Participant__c>();

    
      SFDC_Volunteer_Participant__c sp = 
        (SFDC_Volunteer_Participant__c)TestFactory.createSObject(
          new SFDC_Volunteer_Participant__c(OE_Ambassador_Volunteer__c = ambassador.Id, Volunteer_Event__c = event.Id));

         insert sp;
       
        SFDC_Volunteer_Participant__c oeVolunteer2 = new SFDC_Volunteer_Participant__c();
        oeVolunteer2.OE_Ambassador_Volunteer__c = conRec.id;
        oeVolunteer2.Volunteer_Event__c = oeRec.id;
        oeVolunteer2.Selected_For_Facilitator__c = true;
        oeVolunteer2.Thanks_but_No_Thanks__c = true;
        insert oeVolunteer2;
        
        oeVolunteer2.Thanks_but_No_Thanks__c= FALSE;
        Update oeVolunteer2;
        
        SFDC_Volunteer_Participant__c oeVolunteer10 = new SFDC_Volunteer_Participant__c();
        oeVolunteer10.OE_Ambassador_Volunteer__c = conRec5.id;
        oeVolunteer10.Volunteer_Event__c = oeRec.id;
        oeVolunteer10.Selected_For_Facilitator__c = FALSE;
        oeVolunteer10.Thanks_but_No_Thanks__c = false;
        insert oeVolunteer10;
        
        oeVolunteer10.Selected_For_Facilitator__c = true;
        oeVolunteer10.Thanks_but_No_Thanks__c= true;
        Update oeVolunteer10;
        
        SFDC_Volunteer_Participant__c oeVolunteer = new SFDC_Volunteer_Participant__c();
        oeVolunteer.OE_Ambassador_Volunteer__c = conRec1.id;
        oeVolunteer.Volunteer_Event__c = OErec.id;
        oeVolunteer.Selected_For_Facilitator__c = false;
        oeVolunteer.Thanks_but_No_Thanks__c = false;
        insert oeVolunteer;
        
        SFDC_Volunteer_Participant__c oeVolunteer7 = new SFDC_Volunteer_Participant__c();
        oeVolunteer7.OE_Ambassador_Volunteer__c = conRec1.id;
        oeVolunteer7.Volunteer_Event__c = OErec.id;
        oeVolunteer7.Selected_For_Facilitator__c = TRUE;
        oeVolunteer7.Thanks_but_No_Thanks__c = TRUE;
        insert oeVolunteer7;
        
        
        conRec5.OE_Amb_No_Thanks_Current_Year_Tally__c = -2;
        conRec5.OE_Amb_Selected_Current_Year_Tally__c = -2;
        
        update conRec5;
        
        
        Test.startTest();
        List<SFDC_Volunteer_Participant__c> updateSVPlist=new List<SFDC_Volunteer_Participant__c>();
        List<SFDC_Volunteer_Participant__c> svpList=[select Id,Selected_For_Facilitator__c from SFDC_Volunteer_Participant__c where Selected_For_Facilitator__c=FALSE LIMIT 1 ];
        for(SFDC_Volunteer_Participant__c svp:svpList){
            svp.Selected_For_Facilitator__c=TRUE;
            updateSVPlist.add(svp);
        }
        List<SFDC_Volunteer_Participant__c> updateSVPlist2=new List<SFDC_Volunteer_Participant__c>();
        List<SFDC_Volunteer_Participant__c> svpListFalse=[select Id,Selected_For_Facilitator__c from SFDC_Volunteer_Participant__c where Selected_For_Facilitator__c=TRUE LIMIT 1 ];
        system.debug('svpListFalse are'+svpListFalse);
        for(SFDC_Volunteer_Participant__c svp:svpListFalse){
            svp.Selected_For_Facilitator__c=FALSE;
            updateSVPlist2.add(svp);
        }       
        
        
        Update updateSVPlist2;
        Update updateSVPlist ;
        
        
       
        List<SFDC_Volunteer_Participant__c> oeVolDelete10 = [select id from SFDC_Volunteer_Participant__c where id =: oeVolunteer10.id];
        delete oeVolDelete10;
        
        Test.StopTest();
        System.assertEquals(null,oeVolunteer10.Selected_for_Facilitator_Tally__c , 'selected fac tally should be null as we have initialised with NULL ,thus no modification from OE amb records ');
        System.assertEquals(-1,conRec.OE_Amb_Selected_Current_Year_Tally__c, 'selected current year tally should should get update after change in OE amb volunteer  ');
        
    }    
       static testMethod void testMethodAccExec(){
       
        Test.startTest();
          OEAmbVolCountTallyFields obj = new OEAmbVolCountTallyFields();
        Test.StopTest();
          
  } 
}